### ISSUE TITLE
Add titlebar / menubar

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1027]
This is work in progress: #929

But we're a bit stuck in defining the exact requirements and contents. This needs to be discussed an determined.

**Comment by fatih-erikli** [comment]
In future we may want to implement something like "Open recent" in visual studio code, or "Recently closed tabs" in Firefox. To be able to implement that Multiple-levels contextual menu should be implemented in MenuPanel. We will need a different ticket for that.
