### ISSUE TITLE
'Read-only' / Reviewer mode

### ISSUE THREAD

**Issue by BlackFoundry** [googlefonts/fontra#1050]
It will soon become necessary to have users with read-only access for reviewers.

~They should be able to leave comments and notes directly on a Fontra project.~ (See #58)

Perhaps also have the ability to change the status field of glyphs to mark them 'validated' or any checking preceding step.

**Comment by justvanrossum** [comment]
Also relates to https://github.com/googlefonts/fontra/issues/58

**Comment by justvanrossum** [comment]
Let's separate the read-only mode from comments/annotations. The former is being implemented and is fairly simple, but a proper review system with comments / annotation is a serious project that requires design preparations and planning. Let's use issue #58 for that.

**Comment by justvanrossum** [comment]
For now, we want three modes:
- full editing capabilities
- read-only, selection is possible, but attempting to edit does not work (perhaps shows a dialog)
- "dummy editing": editing is possible, but changes are not written to the backend (this is the current behavior when for example opening a TTF). This is nice to have so someone can play around, get familiar, yet can't destroy the underlying data.
