### ISSUE TITLE
Add "reset all axes" button to right side panel

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#1069]
It'd be very helpful to have a "reset all axes" button in the right panel, similar to the one already in the left panel.

**Comment by justvanrossum** [comment]
You probably know this: you can alt-click on a slider to reset it to its default position. I do understand this can be tedious when there are many axes.

**Comment by mrk-z** [comment]
Yes. I think this is for situations where many axes have been adjusted, and the designer wishes to start again from the default position.

I guess one option is to add the component again, but that would mess up the shape order.
