### ISSUE TITLE
Can't use the python code without npm?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontra#1077]
`pip install -e .` fails complaining about npm. Can we have an option to install that doesn't require npm?

**Comment by justvanrossum** [comment]
Currently no, the build needs Node/npm to be installed, as the [readme](https://github.com/googlefonts/fontra?tab=readme-ov-file#requirements) mentions.

Two solutions:
- Publish on pypi: Node is only required to build a wheel, or to do an install from source. https://github.com/googlefonts/fontra/issues/109
- Separating the font format backend stuff and core Fontra objects  from the Fontra application, into its own library. https://github.com/googlefonts/fontra/issues/548

Both we eventually intend to do.

**Comment by rsheeter** [comment]
Sg, closing as a duplicate of #548
