### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1080]
Hi @justvanrossum and @JeremieHornus and @davelab6 ,

I was wondering if the name of the app is set in stone or if there is still an opportunity to brainstorm? As the app is still in early stage, here are some name ideas for you:

FontSketch
FontDraw
DrawFont
FontRow
iFont
FontDesigner
TypeDesigner 
something with Space
Cosmos
FontCosmos
TypeCosmos
FontWorld
FontSpace
FontPlanet

FontBuilder
Workshop
FontConstructor
FontProducer
TypeTool
FontStudio
FontMaker
FontForm
FontWave
FontStyle
FontStyler
FontWeb

If I compare names of other existing font editors fontra feels a bit clumsy.
'Glyphs' sound warm and nice. 
FontLab is more techy. 
FontForge -> I don't like the name.
Metafont -> I like that name, but it's used already ([https://de.wikipedia.org/wiki/Metafont](https://de.wikipedia.org/wiki/Metafont))
RoboFont -> also techy.

Did you know about: [https://www.glyphrstudio.com/app/](https://www.glyphrstudio.com/app/)?
Or: [https://birdfont.org/](https://birdfont.org/)???

And even if the name is fixed, this little exercise helps me to identify with the project a little more :)

**Comment by ollimeier** [comment]
What the heck, there are quiet a few web-based font editors out there. Here another one: [https://fontark.net/farkwp/](https://fontark.net/farkwp/)

**Comment by ollimeier** [comment]
fontbody
fontfamily
fontloop
LoopType
StudioType

ProType
Stroke
StyleType
VarType
UniType

**Comment by justvanrossum** [comment]
I didn't know fontark, we should check it out.

As far as I'm concerned, Fontra is an excellent name.

**Comment by BlackFoundry** [comment]
Indeed, Fontra is a good name, why are you even thinking of changing it as a start @ollimeier ?
as for the "quite a few" web-based font editors I don't get the point either… 
Fontra's unique approach is:
- variable first (starting at the glyph level)
- collaborative
- suitable large CJK projects (but not only)
The goal is to get a professional tool usable by trained typedesigner in an actual font production workflow… 
I don't think we are targeting the same kind of users FontArk or GlyphR are…

**Comment by anthrotype** [comment]
I vote for Cosmos! 🤣 

No, jokes apart, Fontra is a great name and I see no reason to change it.

**Comment by justvanrossum** [comment]
Fontra has been presented in public several times, we have more than 8 repositories using "Fontra" as a name, we have the  fontra.xyz website, we actively use "fontra" as a subdomain for our private deployment, our team has been working with Fontra for close to two years, people generally seem to like the name, it does not conflict with competing products, etc. etc. I'm afraid this is not open to discussion anymore. I will close the issue.

PS: we even had stickers! (I think we should reprint them.)
![fontra-stickers-2](https://github.com/googlefonts/fontra/assets/4246121/1df2594c-3e76-4dc8-b509-2609ea04aaa4)
