### ISSUE TITLE
Add GHA workflow to automatically update pre-commit dependencies

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1098]
dependabot doesn't support pre-commit yet, so we need another solution.

Fabio has an example workflow file that would do this on a monthly basis, which is perfect.

**Comment by fabiocaccamo** [comment]
- [ ] `fontra`

- [ ] `fontra-rcjk`

- [ ] `fontra-glyphs`

- [ ] `fontra-compile`

- [ ] `fontra-pak`

- [ ] `django-robo-cjk`

**Comment by justvanrossum** [comment]
I'm giving up on this approach: isn't really working well enough, so I'll take it on me to do regular pre-commit updates manually every once in a while.
