### ISSUE TITLE
Rename getUnicodeFromGlyphName() to getCodePointFromGlyphName()

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1099]
There are many instances in the code where we use the word "unicode" instead of "code point", but this is just one. We should make it a habit to always use the term "code point" consistently.

**Comment by justvanrossum** [comment]
This is for @fatih-erikli or @ollimeier, whoever is quicker.

**Comment by ollimeier** [comment]
@fatih-erikli  and @justvanrossum I take it.
