### ISSUE TITLE
Clicking on the overlay of a dialog does not close it

### ISSUE THREAD

**Issue by fatih-erikli** [googlefonts/fontra#1122]
It should I believe. `Esc` key does close the modal when it is pressed.

**Comment by elevchyt** [comment]
I'd like to work on this issue if it's ok.

**Comment by justvanrossum** [comment]
> I'd like to work on this issue if it's ok.

Hi @elevchyt, thank you for your offer! Please, feel free to give it a shot. We can guide you if needed.

**Comment by elevchyt** [comment]
> > I'd like to work on this issue if it's ok.
> 
> Hi @elevchyt, thank you for your offer! Please, feel free to give it a shot. We can guide you if needed.

https://github.com/googlefonts/fontra/pull/1124

Just created a pull request for this, if you don't mind linking it to the issue.
