### ISSUE TITLE
Menu panel should support typing the menu title to select it

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1123]

**Comment by elevchyt** [comment]
From my understanding, this issue refers to focusing on elements of the right-click menu based on their alphabetical order?
For example in the image, if the user presses "C", then "Copy" should be focused first, then if they re-press "C" the "Cut" option should be selected and so on.

![image](https://github.com/googlefonts/fontra/assets/50188474/096b3d3b-57e0-4e0f-ab40-07e1ab0e97f0)

If this is it, I'd love to try solving this issue!

**Comment by justvanrossum** [comment]
I think it's a bit more involved than that: the user just starts typing one or more letters, and the first item matching those letters should be selected. I notice (on macOS) that what you describe also works, but I never noticed that before.

**Comment by elevchyt** [comment]
Understood, I'll post results soon.

**Comment by elevchyt** [comment]
https://github.com/googlefonts/fontra/pull/1127
