### ISSUE TITLE
Menu panel doesn't support "Enter" presses to confirm selection

### ISSUE THREAD

**Issue by elevchyt** [googlefonts/fontra#1128]
Having an item selected and pressing "Enter" doesn't confirm its selection and throws the error below.

![error on enter](https://github.com/googlefonts/fontra/assets/50188474/ae4a783a-cb18-4e67-bee7-3ccd5de09920)

**Comment by justvanrossum** [comment]
Ah, this must be a regression from a while back :( Great catch!

**Comment by elevchyt** [comment]
Haha thanks, I'll try to fix this one too if that's alright. 😀
