### ISSUE TITLE
[menu bar] Once hovering/clicking, arrow key left and right should navigate to previous/next menu panel

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1134]
<img width="333" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/46a6506f-10af-45e0-b091-0f3dba198657">

**Comment by elevchyt** [comment]
Apologies, I seem to not understand how to make the menu bar appear.
I'm running this in the browser, doing `fontra --launch filesystem test-py\data\mutatorsans`.

Is there some other way to run this?

**Comment by justvanrossum** [comment]
Is your checkout up-to-data? This was merged this morning only.
