### ISSUE TITLE
Selection info shows scroll bar

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1175]
Feedback from user Mark:

Not sure if this is intended: now on the right panel, when the panel is too narrow or if the entry name is too long, we get a horizontal scroll bar under the name. But when I scroll to the right I still can’t see the whole name. :sweat_smile:

![Capture d’écran 2024-03-07 à 15 25 25](https://github.com/googlefonts/fontra/assets/21055547/2395c2e5-09e3-4f37-903d-75387e2b2d7d)

**Comment by ollimeier** [comment]
A solution for not displaying the scrollbar might be:
```
-ms-overflow-style: none;
scrollbar-width: none;
```

**Comment by navv-1** [comment]
I think just change `overflow-x: auto;` to `overflow-x: hidden;`

**Comment by ollimeier** [comment]
@navv-1 Sure, overflow-x: hidden; will remove the scroll bar,BUT you won't be able to scroll at all in x direction. So, no possibility to read the full name.

**Comment by ollimeier** [comment]
@justvanrossum and @navv-1 I would prefer to be able to scroll, but hide the scroll bar:
https://github.com/googlefonts/fontra/pull/1180

**Comment by justvanrossum** [comment]
The name should be truncated with "...", scrollable at that small space makes no sense to me at all.
