### ISSUE TITLE
[feature] pressing space bar (fill mode) also activates the hand tool for panning

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontra#121]
Hey, I just tried this for the first time and I love it already!

I have a UI/UX suggestion. It'd be nice if, while pressing the space bar and in black-on-white fill mode, the hand tool were also activated such that one can pan around by dragging the cursor.
I think also other font editors do this (I forgot if it's Glyphs.app or Robofont or both, don't have a mac right now to confirm).

Anyway, thanks for considering.

**Comment by justvanrossum** [comment]
Scroll gestures on a trackpad should still work while holding the space bar, though.

If you press space mid-selection-drag, the selection dragging just continues, so you can tweak "blindly" while looking at a clean view.

That doesn't necessarily prohibit your proposal, and we should consider it.

**Comment by anthrotype** [comment]
yeah, I see what you mean. That's cool too, but I think you can still detect if you're in the middle of a mouse drag and in that case _not_ toggle the hand tool when the space bar is pressed.

**Comment by justvanrossum** [comment]
Yeah, if the mouse is up, we can switch to the hand tool.

It's two things combined then:
- space bar is a shortcut for the hand tool
- spare bar shows a clean view

**Comment by anthrotype** [comment]
yeah, and the space bar only _temporarily_ activates the hand tool while it's being pressed, upon release it switches back to whatever was the last one

**Comment by justvanrossum** [comment]
Indeed, that was so obvious in my mind that I didn't bother spelling it out :)

**Comment by punchcutter** [comment]
I was about to open this same request, but here it is so +1
