### ISSUE TITLE
Font size in text inputs is smaller than labels, in Safari

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1219]
Safari:
<img width="375" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/285ec430-a7ea-46b8-bb44-79d4c5f0dbc7">

Chrome:
<img width="417" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/0fdcc65b-704a-48cd-addc-608749cab880">

How it looks in Chrome is what is intended. What could cause this difference?

**Comment by justvanrossum** [comment]
@ollimeier, @fabiocaccamo, if you have any ideas, let me know.

**Comment by justvanrossum** [comment]
It is not specific to the font info view, you can also see it in the component selection info ("five", the numbers):

<img width="260" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/661b954a-823b-4ec9-afae-f95f399a145c">

**Comment by fabiocaccamo** [comment]
@justvanrossum @ollimeier unfortunately browsers don't use all the same default values, and dealing with issues like this is a never ending work (and consequently a waste of time). 

A good and common practice is using a "CSS reset" like [normalize.css](https://necolas.github.io/normalize.css/) or [sanitize.css](https://csstools.github.io/sanitize.css/) to avoid these kind of issues across the whole project (once for all).

**Comment by justvanrossum** [comment]
It turns out this can be fixed by being specific about the font-size (learned from normalize.css).
