### ISSUE TITLE
Issues with start- and end-point

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1228]
When creating an ellipse shape the start- and end-point are separated into two points:

<img width="1624" alt="Screenshot 2024-03-20 at 13 57 47" src="https://github.com/googlefonts/fontra/assets/21055547/bc933f6c-e016-411d-8013-4d2bbbe1c857">

Note from @justvanrossum:
We may have to fix this in VarPackedPath.closePath()

**Comment by justvanrossum** [comment]
Given we are looking at alternative ways to implement what you're working on, I feel it is premature to open an issue for this. 

The pen-like methods in VarPackedPath mostly exist for convenient testing, and are not used elsewhere in the code base. There are more limitations apart from this closePath() issue, and I don't want to invest right now in these methods.
