### ISSUE TITLE
getSelectionBounds for StaticGlyphController

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1266]
I think we're still only using the on-curve points here.

Ideally, I think StaticGlyphController should get a method `getSelectionBounds(selection)` that would do the right thing given our "sparse" selection.

Maybe we should do this as a follow-up PR, and not let this improvement delay the landing of this PR.

_Originally posted by @justvanrossum in https://github.com/googlefonts/fontra/pull/1247#discussion_r1558998755_

**Comment by justvanrossum** [comment]
For paths, it can use the `filterPathByPointIndices()` function, and compute the (tight) bounds from that. Union the result of that with the component bounds, which the `StaticGlyphController` already has.
