### ISSUE TITLE
[feature request] glyph locking

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1305]
Eventually we want to be able to lock glyphs, and have per-user permissions about it, so that for example a project manager can lock a glyph.

For now, we want a more "cooperative" locking scheme: there will be a button/checkbox to change the locking state of a glyph, but anyone can change it. It will just serve as a small hurdle against accidental editing.

The UI (checkbox, in the form of an lock/unlock icon?) should probably be part of the glyph selection info panel. The locking state would be stored as an item in the glyph's customData dict.

**Comment by ollimeier** [comment]
from Just -> Approach:

- UI (lock/unlock icon in selection info panel, maybe near glyph name or something)
- store flag in glyph.customData
- make editor respect flag by refusing to edit (similar to read-only mode)
- figure out how to store that flag in various backends (rcjk first, then designspace)
