### ISSUE TITLE
Decompose component: include anchors

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1315]
TODO: 
Include anchors when decomposing a component. 
(This is not the case currently.)

**Comment by hwoongkang** [comment]
May I try to fix this issue?

**Comment by justvanrossum** [comment]
@ollimeier, what do you say? I would say yes, but since you're the assignee, you can decide.

**Comment by ollimeier** [comment]
> May I try to fix this issue?

@hwoongkang Yes, please.
