### ISSUE TITLE
[add anchor] Name should be selected when the dialog opens

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1339]
So that the user can immediately type an anchor name.

Or: should it use the placeholder mechanism when creating a new anchor?

Either way, currently the user has to select the suggested anchor name before they can type a new name, which is awkward.

**Comment by ollimeier** [comment]
@justvanrossum Either I do not understand the issue or I cannot reproduce it. Please see the following screen recoding as a reference. Do I do something wrong or has this issue been solved already in the meantime?

https://github.com/googlefonts/fontra/assets/21055547/9aa029a7-e8d8-403b-8fbe-5a05d6b0bc95
