### ISSUE TITLE
[outline editing] interactive resizing of selection via bounding box controls

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1368]
This should also implement https://github.com/googlefonts/fontra/issues/603 (tweak "width" and "height" component axes to match size if possible), but perhaps that is better done as a separate task.

**Comment by ollimeier** [comment]
Notes related to 'rotation': 

https://helpx.adobe.com/indesign/using/transforming-objects.html#transform_objects_with_the_free_transform_tool

https://www.youtube.com/watch?v=HRbvuv_baUo
