### ISSUE TITLE
Display and edit vertical font metrics

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1405]
Related #78

Goal is to have support for vertical metrics by end of next week (Thursday, June 6th).

TODOs:
- [x] #1408
- [x] #1406
- [x] #1411
- [x] #1423
- [x] #1424

Just has some refinements in mind to improve the handling of the font sources in general, which is a big improvement but also a big change in the infrastructure. This will be the basis for further work.

We may want to split this task into several smaller tasks.

**Comment by justvanrossum** [comment]
Fixed by #1424.
