### ISSUE TITLE
Add new guideline, but guideline visualization is off

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1414]
User feedback: 
It's strange when adding a new guideline it will not show it when the guideline visualization is off. 
See demo video:

https://github.com/googlefonts/fontra/assets/21055547/2d6b405c-b96a-4cee-b2f5-75f1f04f34a6

Possible solution:
1. set guideline visualization to 'On' by default
2. when adding a new guideline turn on the visualization (does not matter what setting it was about)

@JeremieHornus comment: _i feel there should be no option, like for anchors: always visible_

**Comment by justvanrossum** [comment]
I think it should at least be on by default, but also: as soon as you add a guideline, it should also be set to on.
