### ISSUE TITLE
[fontra-workflow] Need a way to set OVERLAP_SIMPLE for designspace/UFO export

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1450]
This is to prevent rendering artifacts when outlines overlap exactly at the edge of a shape.

**Comment by anthrotype** [comment]
pls make sure you use https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#publictruetypeoverlap which ufo2ft/fontmake will understand and use

**Comment by justvanrossum** [comment]
Thanks, yes, that's what I am doing.
