### ISSUE TITLE
Hope Fontra has an official Chinese name

### ISSUE THREAD

**Issue by buwuzhengyedexiaoji** [googlefonts/fontra#1461]
This software has a new nickname, “字挼 (zìruá)” among the Chinese font designer community. Within this context, the term “字” serves as a free translation for “font”, while “挼” is a transliteration of “-ra”. The whole translation means “to touch the glyphs”. I believe it’s worth considering this name as the official Chinese translation. Hope you’ll take my suggestion into account.

**Comment by LittleWhiteDoge** [comment]
+1
That will be a great translation 😘

**Comment by justvanrossum** [comment]
After internal discussion weve decided not to go with this name.
