### ISSUE TITLE
Improve UI of font sources panel

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1466]
It works, looks good for now and is consistent with other parts of the panel, but we may want to consider to improve it in some points. If possible keep this in mind while working on other items. Also keep in mind that this may also be used for avar2 editing.

**Comment by justvanrossum** [comment]
After #1711, I think we should at least increase the minimum height of the source boxes somewhat.

Other ideas:
- start with all boxes expanded, and have a way for the user to say "collapse everything" (say: alt-click on the chevron)

**Comment by ollimeier** [comment]
@justvanrossum @JeremieHornus:

Here a quick an dirty idea for this issue above, a 'one-liner' with the most important infos when the cards are folded:

https://github.com/user-attachments/assets/09e3f093-b1b3-41a3-bc7d-a26a43c99a4e


It's far from a PR, but if you're interested in the code, it's this branch:
https://github.com/googlefonts/fontra/tree/issue-1466-improve-ui-font-sources-panel

**Comment by justvanrossum** [comment]
Good thinking. This sounds like a good path forward.

(I'd still like to see all panels expanded by default.)

Maybe only the name and the location should remain. I'm not sure why we'd include the italic angle but none of the line metrics.

The location could be formatted like this:
```
Vertical=100, Horizontal=200, Weight=400
```

We should probably make the location "dense" before displaying: ensure it includes axes that are at the default.

Perhaps we can leave out the labels: "Regular" says enough, we don't need "Name: Regular".

For the location string: we could format axes that are at the default differently, maybe make them bold or italic. Or the opposite: make them gray.

**Comment by ollimeier** [comment]
Some further notes from a discussion with @justvanrossum : Make the whole menu of the panel sticky in both directions: vertically AND horizontally. Only the right content with the cards should move in both directions.

**Comment by ollimeier** [comment]
@justvanrossum 

This is what I changed:
- Make the menu stick to the top left corner
- refactor the current code
- remove italic info from oneliner. Only keep name and the location.
- location formatted like this: Vertical=100, Horizontal=200, Weight=400
- it now includes axes that are at the default
- I removed the labels 'Name' and 'Location'
- I made the default values of the location gray

This is the draft PR: https://github.com/googlefonts/fontra/pull/1739
