### ISSUE TITLE
Add "remove overlap" function

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1514]
- It should take the selection into account:
  - Only work on selected contours
  - Could we make it work on a _partially_ selected contour? This may be hard to do.
- We do not have JS implementation (long term I hope Kurbo + JS bindings will be the solution) so we are for now stuck with doing it in Python:
  - Send the selected outlines to the server, perform remove overlap, send result back (as we do with clipboard conversion and glyph name / code point lookups)
- Use skia-pathops rather than booleanOperations. The former supports quadratics. But perhaps we should be able to use both, as the tradeoffs between skia-pathops and booleanOperations aren't super clear-cut.

**Comment by ollimeier** [comment]
I would see 'remove overlap' as part of a collection of tools similar to this:
https://help.figma.com/hc/en-us/articles/360039957534-Boolean-operations

And similar, to what we did with our 'shape tool' (in a drop down menu).
@justvanrossum Do you agree?

I am not saying, that we need to create all of it at once, but more as a vision for future + as a reference where to put the tool and how to build it so it's prepared for future?!

**Comment by justvanrossum** [comment]
> And similar, to what we did with our 'shape tool' (in a drop down menu).

I can also see this become part of the Transform panel.

**Comment by justvanrossum** [comment]
> but I don't understand how it's possible to send selected outlines to the server, modify them via python and get them back

Search for `parseClipboard()`, you'll find this in server-utils.js and serverutils.py.

Functionality we must support:
- perform "remove overlap" on all selected contours ("Union selection")

Functionality we should consider (a la the Figma examples):
- Subtract selected contours (from remaining contours)
- Intersect selected contours (with remaining contours)
- Exclude selected contours (from remaining contours)

Practically:
- Find which contours are selected
- Make path A containing the non-selected paths
- Make path B containing the selected paths

Depending on the operation, send path A or path A and B to the server.

Suggested function name + signature:

- unionPath(pathA, pathB)  // A | B
- unionPath(path)  // Remove overlap for path
- subtractPath(pathA, pathB)  // A - B
- intersectPath(pathA, pathB)  // A & B
- excludePath(pathA, pathB)  // A ^ B

At the Python level, we may want to support booleanOperations _and_ skia-pathops. Each have their pros and cons. Only skia-pathops supports quadratics, so maybe we should start with that.
