### ISSUE TITLE
Literal edge case for the context menu: control-click can immediately trigger unwanted menu

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1523]
Normally, when you right-click or control-click, the context menu will appear next to the pointer.

However, if you control-click / right-click near the right edge or bottom edge, the pointer will be somewhere inside the contextual menu.

Normally, when you right-click / control-click and release the pointer, the menu stays up and you can navigate around to find the menu item you need.

However, in the edge case, this will _immediately_ choose the item the pointer happens to be over. This is clearly undesirable.

**Comment by justvanrossum** [comment]
Hey @hwoongkang, would it interest you to work on this issue?

**Comment by hwoongkang** [comment]
Sorry, had been busy for a while. Yes, it does interest me! I'll try to fix it.
