### ISSUE TITLE
Resize transformation box UX improvements (drag off-curve)

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1556]
From @JeremieHornus 
_another note: I find i slightly annoying to see the transformation box popping out every time I drag an off-curve point_

https://github.com/user-attachments/assets/afe65e4f-d04a-4db6-bbb4-1d20f482ebb8

**Comment by justvanrossum** [comment]
I think the "bounds resize controls" should not be visible during any selection drag.
