### ISSUE TITLE
Strange behaviour for point selection

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1557]
From @JeremieHornus :
_in Safari and Chrome it’s been a few weeks I have observed a strange behaviour for point selection_

https://github.com/user-attachments/assets/c12b5e6e-68cd-4541-8655-9c4f1ff3f888

**Comment by ollimeier** [comment]
{"variableGlyph":{"name":"m","axes":[],"sources":[{"name":"Regular","location":{"weight":400},"layerName":"Circuit-Regular/foreground","inactive":false,"customData":{}},{"name":"Bold","location":{"weight":800},"layerName":"Circuit-Bold/foreground","inactive":false,"customData":{}}],"layers":{"Circuit-Bold/background":{"glyph":{"xAdvance":799,"path":{"coordinates":[342,0,342,321,342,355,338,364,313,372,248,393,237,396,230,399,223,399,212,399,208,393,208,379,208,0,52,0,52,376,52,484,96,550,191,550,218,550,252,544,280,535,353,512,471,475,498,449,498,347,498,0,342,0,342,335,342,423,385,550,565,550,745,550,788,423,788,335,788,0,632,0,632,304,632,362,608,398,565,398,522,398,498,362,498,304,498,0],"pointTypes":[0,8,2,2,8,8,2,2,0,2,2,8,0,0,8,2,2,8,2,2,8,8,2,2,8,0,0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,0],"contourInfo":[{"endPoint":25,"isClosed":true},{"endPoint":43,"isClosed":true}]},"components":[],"anchors":[],"guidelines":[]},"customData":{}},"Circuit-Bold/foreground":{"glyph":{"xAdvance":836,"path":{"coordinates":[342,0,342,306,342,341,338,343,313,357,268,383,260,388,256,389,248,389,228,389,213,389,208,384,208,369,208,0,52,0,52,369,52,494,88,540,208,540,248,540,283,540,303,534,328,520,367,498,471,439,498,444,498,342,498,0,342,0,342,335,342,423,385,550,565,550,745,550,788,423,788,335,788,0,632,0,632,304,632,362,608,398,565,398,522,398,498,362,498,304,498,0],"pointTypes":[0,8,2,2,8,8,2,2,8,8,2,2,8,0,0,8,2,2,8,8,2,2,8,8,2,2,8,0,0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,0],"contourInfo":[{"endPoint":27,"isClosed":true},{"endPoint":45,"isClosed":true}]},"components":[],"anchors":[],"guidelines":[]},"customData":{}},"Circuit-Regular/background":{"glyph":{"xAdvance":881,"path":{"coordinates":[365,0,365,335,365,394,357,410,315,423,225,451,202,458,186,461,178,461,157,461,145,446,145,419,145,0,57,0,57,416,57,500,100,550,165,550,186,550,218,542,252,531,363,495,435,472,453,449,453,374,453,0,365,0,365,355,365,435,403,550,563,550,723,550,761,435,761,355,761,0,673,0,673,333,673,416,633,467,563,467,493,467,453,416,453,333,453,0],"pointTypes":[0,8,2,2,8,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,8,2,2,8,0,0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,0],"contourInfo":[{"endPoint":25,"isClosed":true},{"endPoint":43,"isClosed":true}]},"components":[],"anchors":[],"guidelines":[]},"customData":{}},"Circuit-Regular/foreground":{"glyph":{"xAdvance":814,"path":{"coordinates":[385,0,385,355,385,435,423,550,569,550,723,550,761,435,761,355,761,0,673,0,673,343,673,426,633,467,563,467,493,467,453,426,453,343,453,0,57,0,57,355,57,435,95,550,255,550,362,550,415,484,433,426,453,355,453,0,365,0,365,343,365,426,325,467,255,467,185,467,145,426,145,343,145,0],"pointTypes":[0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,0,0,0,0,8,2,2,8,2,2,8,0],"contourInfo":[{"endPoint":17,"isClosed":true},{"endPoint":36,"isClosed":true}]},"components":[],"anchors":[],"guidelines":[]},"customData":{}}},"customData":{}}}

**Comment by justvanrossum** [comment]
This is the shape in question:
```json
{"layerGlyphs":[{"layerName":"Circuit-Regular/foreground","location":{},"glyph":{"xAdvance":814,"path":{"coordinates":[385,0,385,355,385,435,423,550,569,550,723,550,761,435,761,355,761,0,673,0,673,343,673,426,633,467,563,467,493,467,453,426,453,343,453,0,57,0,57,355,57,435,95,550,255,550,362,550,415,484,433,426,453,355,453,0,365,0,365,343,365,426,325,467,255,467,185,467,145,426,145,343,145,0],"pointTypes":[0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,8,0,0,8,2,2,8,2,2,0,0,0,0,8,2,2,8,2,2,8,0],"contourInfo":[{"endPoint":17,"isClosed":true},{"endPoint":36,"isClosed":true}]},"components":[],"anchors":[],"guidelines":[]}}]}
```

The problem is that there is a segment "overlapping" the point, and the segment gets precedence ofer the point, which is obviously wrong.
