### ISSUE TITLE
Reorganize 'User settings'

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1588]
We discussed that 'Glyph editor appearance' should be part of the main menu bar item 'View', all other items should go into a newly created section/page 'User Settings' similar to what we did with 'font-info-panel'.

Sections: 
- Clipboard export format
- keyboard shortcuts (customizable)
- General Infos (like Python version, etc.)

**Comment by justvanrossum** [comment]
Superseded by #1651.
