### ISSUE TITLE
Unable to save UFO in Ubuntu Linux - fontra compled from source 

### ISSUE THREAD

**Issue by mitradranirban** [googlefonts/fontra#1620]
I want to create a variable font. I am quiet a novice and want to use Fontra for that 
I have created two source UFO files and one design space file in my repository. Now I am using fontra --filesystem command to open the repository. I can open the .designspace and source UFO files from fontra, make changes but can not save the changes and there is not option to save as UFO in Ubuntu Linux version 
Screenshot attached 
![Screenshot from 2024-08-28 13-52-39](https://github.com/user-attachments/assets/acbaeef7-f917-4836-9f2c-35e1a006f364)

**Comment by mitradranirban** [comment]
The files I am using can be seen at https://github.com/mitradranirban/samaano-fonts/tree/main/sources

**Comment by justvanrossum** [comment]
Saving is automatic and immediate: there is no save button. You should see the changes you make in Fontra in the UFO files immediately.

**Comment by mitradranirban** [comment]
Thanks
