### ISSUE TITLE
Migrate plugins and “gear” tab items to app settings and menu bar

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1651]
The goal is to get rid of the gear tab completely.

- [x] #1656
- [x] #1673
- [x] #1668
- [x] #1675

Migrate Experimental features settings:
- [x] #1679
- [x] #1671
- [x] #1677

Final steps:
- [x] #1694
- [x] #1693
- [x] #1700

**Comment by ollimeier** [comment]
@justvanrossum Do you have anything in mind, what to do with 'Display Language' and 'Theme settings'? Where should this go? It is not listed above, yet.

**Comment by justvanrossum** [comment]
Both should go to application settings.

**Comment by ollimeier** [comment]
> Both should go to application settings.

As separate pages or bundled into one, for example under 'User settings'?

**Comment by ollimeier** [comment]
Here is a draft PR which bundles the topics under 'User settings': https://github.com/googlefonts/fontra/pull/1674

**Comment by ollimeier** [comment]
Sadly, I don't understand what "Scaling edit tool behavior" does. This is the reason why I have not touched it, yet.

**Comment by justvanrossum** [comment]
> Scaling edit tool behavior

Find a glyph with a shape like this:
<img width="385" alt="image" src="https://github.com/user-attachments/assets/a00b66fa-e92d-455a-a55b-feb98f76ee8d">

Move the selected point left and right, and compare with the "scale edit behavior", esp. look at the horizontal handles nearby.

**Comment by ollimeier** [comment]
@justvanrossum The docs page has been updated. So, the last TODO bullet point would be to delete the 'gear' sidebar panel. The question is, how long do we want to keep both?

**Comment by justvanrossum** [comment]
TBH, I think we should just delete it.

**Comment by justvanrossum** [comment]
🥳 🎉
