### ISSUE TITLE
Image in background for tracing

### ISSUE THREAD

**Issue by bghryct** [googlefonts/fontra#1660]
I am using fontra to teach basic type design and lettering to college undergraduate students. They are drawing by hand on paper initially and it would be nice to have support for drag and drop image placement as in glyphs robofont etc. the ability to work from a sketch is pretty important imo.

**Comment by justvanrossum** [comment]
I agree, and we definitely want to support this. I added it to the roadmap, where it should have been all along: https://github.com/googlefonts/fontra/commit/b3601085621f6b8be869767268b6abeabf8bdfa8

**Comment by justvanrossum** [comment]
This has been implemented now, and will be available in tonight's Fontra Pak build.
