### ISSUE TITLE
Dialog's default button doesn't respond to enter key in some cases

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1702]
Open a glyph in read-only mode (either lock it, or open a .ttf or .glyphs file).

Select some points. If you try to drag the points, you get the `Can’t edit glyph “xxx”` dialog. You can dismiss it with the Escape key or the Enter key.

Now, with the same selection, try to scale or rotate the selection with the bounding box handles. The same dialog appears. You can dismiss it with the Escape key, but _not_ with the Enter key, despite the Okay button being the default.

Does the dialog not get the proper focus in this case?

Or is some other event handler stealing the event?

Is this issue specific to the transform-with-bounds-handles, or is there a more general cause?

**Comment by ollimeier** [comment]
First test: It seems to be specific to the transform-with-bounds-handles.
