### ISSUE TITLE
Font info/sources panel

### ISSUE THREAD

**Issue by MauriceMeilleur** [googlefonts/fontra#1711]
I don't think this is related to #1466 but apologies if I'm wrong: the UI for Font Info/Sources is apparently complete but the display is cramped and scrolling through the items difficult; see attached screenshot. Behavior is the same MacOS/Win.
[Image](https://github.com/user-attachments/assets/8e56110d-0d6b-4659-ba00-4b437936d676)

**Comment by justvanrossum** [comment]
The little chevron at the top left of the box should expand it. (It's perhaps silly it is collapsed to begin with, but we've been mostly looking at fonts with many sources. But yeah, this is one of the aspects we're not quite happy with.)

The scrollbars should ideally only show when needed. Do you have a global pref set to always show scrollbars, or do you use a pen tablet of some kind?

**Comment by MauriceMeilleur** [comment]
I'm using Chrome on MacOS and I'll check my prefs, but knowing about the chevron fixes the problem! Thanks, Just.

**Comment by justvanrossum** [comment]
Ideally Fontra's UI shouldn't turn to sh*t depending on users pref settings, but knowing about them may help us improve. Let me know if you find something. It could be this, in the Appearance panel in System Settings:
![Image](https://github.com/user-attachments/assets/923962d2-d511-44b1-8bf9-9977e7ff80ca)

**Comment by justvanrossum** [comment]
(I took the liberty to edit your initial report to show the image inline)
