### ISSUE TITLE
App settings (and Font Info?) Title sidebar width should be flexible

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1717]
Its current width is too tight for some translations:

![Image](https://github.com/user-attachments/assets/58e053a5-919e-4bba-825b-b03269213fbb)

**Comment by justvanrossum** [comment]
This is fixed by #1719.

**Comment by ollimeier** [comment]
Please see also: https://github.com/googlefonts/fontra/pull/1739#discussion_r1810927015
