### ISSUE TITLE
Error when changing slider within sources panel

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1746]
The error:
```
var-model.09e4d81f.js:287 Uncaught RangeError: Too many properties to enumerate
    at Function.keys (<anonymous>)
    at locationToString (var-model.09e4d81f.js:287:28)
    at SourceBox.checkSourceEntry (panel-sources.09e4d81f.js:381:19)
    at SourceBox.checkSourceLocation (panel-sources.09e4d81f.js:363:17)
    at Object.listener (panel-sources.09e4d81f.js:464:17)
    at observable-object.09e4d81f.js:115:31
```

This error appears when changing a slider of a source within the sources panel. But not for every font. So far I tested:
Egitto.designspace: Error.
AmstelvarA2-Roman.designspace: Error
RobotoFlex.designspace: Error

MutatorSans: No error.
DemoAvar2.designspace: No error in the console of the font info page, but the editor page console has this info:
```
error while interpolating font sources 
{message: ': locations must contain default (missing base source)', type: 'model-error'}
```

Further observations:
When reloading the font info page (AmstelVar, Egitto, RobotoFlex), the change in the source is gone (not saved to the file).

This all happens with the 'main' branch.

**Comment by ollimeier** [comment]
The checks seem to be very inefficient. I'll have a look if I can make it better.

**Comment by justvanrossum** [comment]
Observed while reproducing with Egitto: it takes a few seconds before the error appears.

**Comment by justvanrossum** [comment]
There's something very wrong with the location sent to locationToString:

![Image](https://github.com/user-attachments/assets/44607827-3350-4ad2-8e27-27720cb96e6a)

At the end:

![Image](https://github.com/user-attachments/assets/b3dd725c-e007-474d-854e-aee19a5a0a15)

**Comment by ollimeier** [comment]
Yes. I am on it.
