### ISSUE TITLE
Change log with major updates

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1748]
A person from our major user team was not aware of the UI change that the gears panel is gone, now.  Even though we announced it at the last  fontra demo 4, we cannot expect everyone to watch it.

This leads to the fact, that we may need a change log with major updates people can read.

Notes from Just:

- On the one hand we should maintain a fairly detailed changelog (“bug 123 got fixed in PR 456”), on the other hand it would be nice to ha ve a concise overview of new features and changes.
- I was also thinking it would be nice to have a blog, where we could post small articles with updates.
- But a page on the website with a high level overview of changes would be great.
- Or if we find a form for the changelog to be useful for both cases: have CHANGELOG.md in the repo, and publish a styled version as a page on the website.
- For the FontGoggles website I have a script that reads .md and generates .html: https://github.com/justvanrossum/fontgoggles/tree/master/docsSource
- This is the CHANGELOG.md for FontGoggles: https://github.com/justvanrossum/fontgoggles/blob/master/CHANGELOG.md For each release I make bullet points for each non-trivial change.
- Since we don’t to releases yet, I think we should just use the current date whenever we summarize recent changes.
- If we go that route (publish a styled version of the CHANGELOG.md on the website, we should also look into RSS, and how we can generate an RSS feed to people can subscribe to changes to that file. (With an RSS reader. I’m afraid I’m not an RSS user, but I think it’s a useful mechanism, that has some popularity)

**Comment by justvanrossum** [comment]
This has been fixed by #1749 and by changes to the website.
