### ISSUE TITLE
Right Click Shortcut Menu Items Not functioning now

### ISSUE THREAD

**Issue by mitradranirban** [googlefonts/fontra#1755]
I am creating a variable font using Fontra.
The Right click shortcut menu used to be very heplful but most menu items like cut copy paste are inactive now, so I have to use keyboard shorcuts instead 
Screenshot attached ![Image](https://github.com/user-attachments/assets/9643a400-0897-4792-97eb-2e261b63c592)

**Comment by mitradranirban** [comment]
Fontra version:
0.1.dev9562+gbe8268b
Python version:
3.10.12
Startup time:
2024-10-25T16:08:52+00:00
View plugins:
applicationsettings, editor, fontinfo
Project manager:
FileSystemProjectManager
OS: Ubuntu 22.04

**Comment by justvanrossum** [comment]
Thank you for reporting. I can confirm this is a bug. I'll look into it.
