### ISSUE TITLE
Bug: using knife tool with multiple editor windows

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1869]
When using the knife tool in one editor window another editor window breaks.
I first noticed it while testing **#1863 Clarify server API**, but it's not related to this branch. It breaks in our **main** branch as well.

https://github.com/user-attachments/assets/d976d577-808d-466c-9f51-d36799b8fa08

Error:
<img width="855" alt="Image" src="https://github.com/user-attachments/assets/d9b72849-571c-4fd5-a15a-42bb379d82bf" />

**Comment by justvanrossum** [comment]
Ouch.
