### ISSUE TITLE
Add knife tool

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#190]
Relates to #9 and #30

**Comment by justvanrossum** [comment]
How to behave with multi-source editing is to be determined:
- Should other layers follow the knife line? (This may break compatibility)
- Should other layers follow the proportional interesection points? (Keeps compatibility, like pen tool "insert point")

**Comment by ollimeier** [comment]
@justvanrossum I started with setting up the KnifeTool as a new tool and visualize a straight line via mouse click and drag. But now I need help/support/advice. In general I think what we need are the intersection points. With these point we can break the contours and close them again. But I don't know how to calculate the intersection of contours/lines/paths. 

Thanks a lot in advance. The branch is this: https://github.com/googlefonts/fontra/tree/issue-190-knife-tool

**Comment by justvanrossum** [comment]
> what we need are the intersection points 

The powerruler uses `pathHitTester.lineIntersections`, which is almost the right thing, except that it computes the intersections with an endless ray, not with a line between two points. The math is all there, but we probably need to refactor that we can reuse the same math for both use cases.

**Comment by justvanrossum** [comment]
Plan:

- Rename `lineIntersections()` to `rayIntersections()`
- Add a new method `lineIntersections(p1, p2)` that returns the intersections between p1 and p2.

This following will be the heart of the new `lineIntersections(p1, p2)`:

https://github.com/googlefonts/fontra/blob/b9e66cf1cb8dac37347116619b7824576f0ec372/src/fontra/client/core/path-hit-tester.js#L85-L100

I think it should be possible to write `lineIntersections(p1, p2)` in such a way that `rayIntersections()` can use it.

It is probably easiest to keep the `extraLines` stuff in the new `lineIntersections(p1, p2, extraLines)` method, even though we don't really need it there, from an api-standpoint. The new `lineIntersections(p1, p2, extraLines)` method is pretty much the second half of the current `lineIntersections()` method, and `rayIntersections()` is the first half, and calls `lineIntersections()` at the end.

(The `findIntersections()` function does the hard work, `bezier-js` / `bezier.lineIntersects()` does the hard-hard-work.)
