### ISSUE TITLE
Make fontra read/write TTF with FontTools implementation of Variable Composites

### ISSUE THREAD

**Issue by JeremieHornus** [googlefonts/fontra#228]
https://github.com/fonttools/fonttools/tree/varc

test data:
https://github.com/fonttools/fonttools/blob/varc/Tests/ttLib/data/varc-ac00-ac01.ttf

**Comment by justvanrossum** [comment]
Read yes, but write maybe not. Writing TTF/OTF directly is currently not planned, and should be handled by fontmake.

**Comment by justvanrossum** [comment]
Writing is for now out of scope.
