### ISSUE TITLE
[deployment] Browser cache is a problem with updates

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#229]
We need a way to ensure the latest versions of JS and CSS files are taken.

Fontra has a weak attempt at reloading automatically, but this doesn't work reliably in practice. 

I hear a common technique is to add a hash of the file contents to the filename. This requires filtering all sources that reference them.

I'm curious what the common solutions to this problem are.

This also affects [Fontra Pak](https://github.com/BlackFoundryCom/fontra-pak), which is unintuitive as it intends to be a standalone application.

**Comment by justvanrossum** [comment]
@fabiocaccamo do you have experience with this topic?

**Comment by justvanrossum** [comment]
I went for a simpler approach by using a single random token per Fontra server launch. Adding a file hash would perhaps be better, but this was much easier to implement.

**Comment by fabiocaccamo** [comment]
@justvanrossum generally when I face this problem, the solution I use depends by the context, if I'm working on top of `django` framework I simply set `STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'` which does all the dirty job, but it works together with `{% static "filepath" %}` template tag for generating the files URLs correctly.

In the other cases, generally I do what you already did, I add a "cache buster" parameter to file's URL, the parameter could contain the version *(for security reasons, a good practice is to never disclose the version of anything)* or even a random value if you need to be sure that the file is downloaded every time. 

The drawback of this approach is that when the version changes all files get re-downloaded, even those that are not changed from the previous version, this is not good from a scalability point of view.

Considering the current stage of the project, I think that this solution is ok for now.

**Comment by justvanrossum** [comment]
> The drawback of this approach is that when the version changes all files are re-downloaded, even those that are not changed from the previous version, this is not good from a performance/scalability point of view.

Yeah, that's my concern as well. But also thought that it's currently not a big deal. Thanks!
