### ISSUE TITLE
Consider using Prettier for front end code formatting

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#233]
https://www.npmjs.com/package/prettier

@nedkamburov

**Comment by justvanrossum** [comment]
Would be great if you could post some example snippets of what Prettier would do to the Fontra code base.

**Comment by nedkamburov** [comment]
Oh, yeah, I can do it and maybe make a separate branch and PR and we can review the changes directly here.

**Comment by justvanrossum** [comment]
I would first like to get a rough idea of what it's opinions are, and what we may want to configure.

**Comment by justvanrossum** [comment]
I'm especially curious what it does with long lines.

**Comment by nedkamburov** [comment]
We will see what happens by default and we can configure it, no problem.

**Comment by justvanrossum** [comment]
Later we should use https://pre-commit.com/ and automate use of black, isort and prettier with it.

**Comment by nedkamburov** [comment]
I have created a separate branch so we can review the changes directly. No merge or PR yet.
https://github.com/googlefonts/fontra/tree/prettier-migration

**Comment by nedkamburov** [comment]
I cannot leave this in the .prettierrc but it's a handy reference for prettier configuration options
https://gist.github.com/adbutterfield/6b91625b5b07ca2c29f6322245e3e2bb

**Comment by justvanrossum** [comment]
I like what I'm seeing in the prettier-migration branch. I will have to fix this bit:

https://github.com/googlefonts/fontra/blob/f42d8dc3eeae327eaad76050b1fdcac5f08f8512/src/fontra/core/server.py#L220-L236

...which isn't unit-tested, hence the tests pass :)

I will:
- [ ] write a test for that code (possibly refactoring it to make it more testable)
- [ ] fix the regex so it can handle single quotes

That code is quite dodgy either way, and may cause future headaches, but I'm not yet sure what the best route is to fix that.

**Comment by nedkamburov** [comment]
Sounds good!

**Comment by justvanrossum** [comment]
black uses 88 as the maximum line length. Would it be very weird to also use this value? I find even 88 quite short, but that's apparently what the Python community (mostly) agrees on.

**Comment by nedkamburov** [comment]
80 columns is based on standard CL line width, right? So it is quite archaic/arbitrary in that regard. 
To me it makes no difference. I don't think 8 characters will add much more but if you want we can have it that way.

**Comment by justvanrossum** [comment]
I meant to do this as a PR, but I messed up, so it ended up in main directly: https://github.com/googlefonts/fontra/commit/107a4c9d6b0e26b6e192d17ca9191f49a1db1e58

Can you:
- [ ] rebase your branch on main
- [ ] configure the max line length for Prettier to 88
- [ ] run Prettier again
- [ ] open a PR for your branch
