### ISSUE TITLE
Use git pre-commit for automated formatting, linting

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#243]
We should use [pre-commit](https://pre-commit.com/) for the following tasks:

- black
- isort
- flake8 (maybe a subset of checks: unused imports/vars/NameErrors)
- prettier: `npx prettier --write "**/*.{html,css,js,json}"`

To do:

- [x] Here in this repository
- [x] https://github.com/googlefonts/fontra-rcjk
- [x] https://github.com/googlefonts/fontra-pak (Python-only)

**Comment by fabiocaccamo** [comment]
> To do:

- [x] Here in this repository: https://github.com/googlefonts/fontra/pull/272

- [x] https://github.com/googlefonts/fontra-rcjk: https://github.com/googlefonts/fontra-rcjk/pull/39

- [x] https://github.com/googlefonts/fontra-pak: https://github.com/googlefonts/fontra-pak/pull/10
