### ISSUE TITLE
Use fontTools.misc.transform.DecomposedTransform

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#245]
Use fontTools.misc.transform.DecomposedTransform and remove `fontra.core.classes.Transformation`

This requires https://github.com/fonttools/fonttools/pull/2958 to be landed in a fonttools release.

TODO:
- [ ] bump fonttools dependencies in requirements.txt and pyproject.toml
- [ ] Use the conversion code from fonttools to replace makeAffineTransform and decomposeTwoByTwo.
- [ ] Review the skewX issue (fonttools flips the sign compared to the glyf-1 spec)

**Comment by behdad** [comment]
> [ ] Review the skewY issue (fonttools flips the sign compared to the glyf-1 spec)

skewX I believe?

**Comment by justvanrossum** [comment]
> skewX I believe?

Thanks, fixed.

**Comment by justvanrossum** [comment]
This can be done now: https://github.com/fonttools/fonttools/releases/tag/4.39.0
