### ISSUE TITLE
Short-cuts to switch tools

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#247]
I suggest to just start with "command/control 1", and go up from there.

This got mostly implemented in #262.

To do:
- [x] switch to the appropriate cursor #266

**Comment by justvanrossum** [comment]
To be clear, this is about these tools:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/4246121/216935458-1b8cf554-4099-4f31-9ff2-13dd3277245b.png">

**Comment by nedkamburov** [comment]
Implemented 90%
The only thing left to do is to automatically update the cursor when switching the tool.

**Comment by justvanrossum** [comment]
> The only thing left to do is to automatically update the cursor when switching the tool

I'll post a separate PR for that: it needs a new Tool method.

**Comment by justvanrossum** [comment]
Done as per #262 and #266
