### ISSUE TITLE
Need a UI element for editor visualization layer prefs

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#254]
Part of #239.

Maybe as a shallow tree view:
- https://iamkate.com/code/tree-views/

Good candidate for a (Lit-based) web component.

**Comment by justvanrossum** [comment]
- Set up the UI with data, a "description"
- An API for the content data state
- An API for the UI state

**Comment by justvanrossum** [comment]
We could also start with a list of checkboxes. Maybe with sections.

**Comment by nedkamburov** [comment]
I did some testing with the list which seems to work fine. Styling is a bit funky but we can work it out. Also not so important https://codepen.io/nedkamburov/pen/vYzBJMO 

I also did a test in Lit.js and things seem to work well. Reactivity is fine and code logic seems clear enough.
https://codesandbox.io/s/demo-collapsible-menu-layer-preferences-with-lit-js-56bojf?file=/index.html:159-632

In index.html you can see how I pass an array of options. Nothing different, besides it's just passed as a String and Lit converts it back to a normal Array.
```
      pathOptions='[
        {"name": "fill",
         "isChecked": true
        },
        {"name": "stroke",
         "isChecked": false
        },
        {"name": "metrics",
         "isChecked": true
      }]'
```
In layer-preferences.js you can see how the list with inputs is being rendered. 

P.S. There is no reason to separate pathOptions from canvasOptions as they are effectively the same. But I wanted to see how different configurations might work. I like to keep them also as Array of object so we can add more properties if needed.

**Comment by justvanrossum** [comment]
Great, thank you!

I think it would be good for us if we could set up the contents in code instead of HTML.

The top level does not need to be collaplable I think, and the title of the whole thing ("Layer Preferences") could perhaps be separate.

The datastructure could look like this perhaps:

```json
[
  {
    "name": "Path Options",
    "items": [
      { "name": "fill", "isChecked": true },
      { "name": "stroke", "isChecked": false },
      { "name": "metrics", "isChecked": true }
    ]
  },
  {
    "name": "Canvas Options",
    "items": [
      { "title": "guidelines", "isChecked": true },
      { "name": "measurements", "isChecked": false },
      { "name": "grid", "isChecked": false }
    ]
  }
]
```

**Comment by justvanrossum** [comment]
- It's not really a "menu", though. Perhaps "collapsible-options-list" could work?
- I still think we should keep the label for the whole thing ("menuTitle") out of it.
- The open/closed state is a good thing to have, but I'm trying to think how I'd like this to be part of the API, as it is distinct from the state of the checkboxes
- We may need to separate between "name" and "key" (let's ignore that for now while you're trying things out)

**Comment by justvanrossum** [comment]
Or just "options-list".

**Comment by nedkamburov** [comment]
I managed to integrate the demo into Fontra! I think it works well (at least in terms of design and functions nothing changed after the migration) 
One surprising thing is that the `options` attribute is really updated in real time. So on at any time by calling `optionsList.options` returns the up-to-date options. 
However, we need to listen for those changes in `editor.js` and I wrote a dodgy click event listener which works for now but it needs to be reworked. 
I wanted to maybe tie an MutationObserver to it but the actual string property that's part of the Node `<options-list>` is not being updated so it doesn't trigger the observer.

https://github.com/googlefonts/fontra/compare/main...add-layer-preferences-with-component-issue-254

![Screenshot 2023-02-14 at 13 15 38](https://user-images.githubusercontent.com/11830669/218721092-036b5600-7b7a-4b3e-86f4-cd057b0fe66a.png)

**Comment by justvanrossum** [comment]
Thanks! We'll indeed need a better event to listen to than click.

The circled + and - for (un)collapsing: what do you think of using an open/close arrow for that? Or even something like this:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/4246121/218731248-0e71c016-d68f-4a22-bd4b-84e88f8b0339.png">

Ideally if would be a unicode char that looks passable in this context.

▶ & ▼ may be useful.

**Comment by justvanrossum** [comment]
Hmm, they looked like this in "Write" mode: 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/4246121/218732007-64590d88-d5a8-46e1-a23e-b34036789a4d.png">

**Comment by justvanrossum** [comment]
In the worst case we'll add custom shapes to the icon font.

**Comment by nedkamburov** [comment]
I simplified it and removed all styling. Now it's just default browser styling. 

Firefox/Chrome/Safari:
![Screenshot 2023-02-14 at 14 34 17](https://user-images.githubusercontent.com/11830669/218740202-a8a2e720-44f2-4d00-a07a-fe80ad235653.png)
 Microsoft Edge:
![Screenshot 2023-02-14 at 14 34 31](https://user-images.githubusercontent.com/11830669/218740204-62c91fe3-ff7a-4d92-b40e-02c57b0a3c7d.png)
