### ISSUE TITLE
[feature request] Show font name in <title> and/or footer

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/fontra#301]
I have a bunch of different tabs open with some different projects or different parts of the same project and I keep looking around for the name of what I'm looking at. Right now it's all local so I'm getting titles like `Fontra - %2FUsers%2F...fullpath` which tells me what I'm looking at, but I think at least <title> could be set to something like `Fontra - Font Name` or just the basename of the path. But what I'd really like is to have the font name also clearly in the page somewhere like with a page header or footer. A footer/status bar could be really useful for all kinds of things so I vote for that as a possibility.

**Comment by justvanrossum** [comment]
Thanks for your feedback, we will definitely consider. The title bar issue should be relatively easy to fix.

We are broadly considering adding a menubar-ish area at the top, and having the font name there would make sense.
