### ISSUE TITLE
Lit should now become a true dependency

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#343]
TODO:
- [x] Install Lit locally, update package.json etc.
- [ ] Change Lit import in web-components/general-settings.js to the appropriate local path
- [ ] Test that it actually works

**Comment by nedkamburov** [comment]
Does our bundler work with dependencies of the dependencies? 
Lit uses 3 dependencies and they aren't copied when I run `npm run jsdeps`
https://www.npmjs.com/package/lit?activeTab=dependencies

**Comment by justvanrossum** [comment]
Are these dependecies listed in package.json? Probably not. In that case, I *think* jsdeps.py should be expanded to read package-lock.json. @fabiocaccamo?

**Comment by justvanrossum** [comment]
Or even to read package-lock.json instead of package.json?

**Comment by nedkamburov** [comment]
Yes, I imagined that it will do so recursively. Some of those dependencies might also have dependencies so I don't think we can go on without such mechanism.

**Comment by justvanrossum** [comment]
Everything needed is listed flatly  in package-lock.json: all the recursion is resolved by npm.

**Comment by fabiocaccamo** [comment]
I wonder if we should continue in this direction instead of using an existing bundler *(which I'm sure we will do sooner or later)*.

**Comment by justvanrossum** [comment]
> I wonder if we should continue in this direction instead of using an existing bundler (which I'm sure we will do sooner or later).

If you can propose a solution that does what we need using an existing bundler, I'm all ears. But I figured you wrote jsdeps.py because you couldn't find one?

Your idea for jsdeps.py was correct (a simple, somewhat brute-force approach), the only mistake is that you used `package.json` instead of `package-lock.json`.

**Comment by nedkamburov** [comment]
Does this solve any internal import paths at the moment? 
I am able to import `lit` into the web component `import { html, css, LitElement } from "../third-party/lit/index.js";`  but then:
```
Uncaught TypeError: The specifier “@lit/reactive-element” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```
This is what index.js contains:
```
import "@lit/reactive-element";
import "lit-html";
export * from "lit-element/lit-element.js";
export * from "lit-html/is-server.js";
//# sourceMappingURL=index.js.map
```

**Comment by justvanrossum** [comment]
Argh, this may be the nail in the coffin of the jsdeps approach of just copying folders from node_modules :(

Imports within Node are apparently not compatible with the browser: those first imports need to be rewritten in a browser-compatible form. *Unless* there exists a polyfill that makes this style of importing work in the browser.

I think we may need a proper bundler after all.

**Comment by justvanrossum** [comment]
Here is some interesting info: https://guybedford.com/es-module-shims-production-import-maps

**Comment by nedkamburov** [comment]
Yes, that will ease lots of this. I went on to think whether we can write importmaps but I think it's inviting more problems for the future. 
Plus, now we are not doing any minification, tree-shaking which is not too bad to have anyways.

**Comment by justvanrossum** [comment]
What we need, in short, is something that bundles up everything that is not a dev-dependency from node_modules, and outputs either a folder of browser-importable stuff or a single file.

**Comment by justvanrossum** [comment]
(FWIW, the link I posted above links to an import map polyfill)
