### ISSUE TITLE
Fontra 'core' should automatically find a free localhost port when launched in 'filesystem' mode

### ISSUE THREAD

**Issue by BlackFoundry** [googlefonts/fontra#353]

**Comment by justvanrossum** [comment]
This function should move to Fontra:

https://github.com/googlefonts/fontra-pak/blob/04fe5dc9c6e530e56fd518efcc67a57fa99a2022/FontraPakMain.py#L100-L114

(Possibly renamed to `findFreeTCPPort()`)

**Comment by kenmcd** [comment]
You may want to add the ability to specify this port number.
To avoid potential conflicts with some other applications which are not currently running - which use a specific port.

**Comment by fatih-erikli** [comment]
@kenmcd It's possible with `--http-port` argument currently.

```
fontra --http-port 3000 --launch filesystem fonts
```

@justvanrossum If a port has been specified in command line arguments and the given port is not available, we do not seek for a free port, let it to fail. Port search is available only when the port is default (8000). Do you think it's ok?

**Comment by fatih-erikli** [comment]
Or you are aware the command line argument and you want free port search to work when a specific port is explicitly given? @kenmcd
