### ISSUE TITLE
[CJK Design Frame] making it following the sources width

### ISSUE THREAD

**Issue by GaetanBaehr** [googlefonts/fontra#412]
Would be very nice to have the CJK design frame that resize to the selected source width. 

Just the width of the frame should change

**Comment by mrk-z** [comment]
It'd be also great to have the Design Frame keep different values based on layers.
In GS Flex, the Hairline and Extrabold have different Character Face Rate than the Regular and Bold, so it'd be convenient to not have to change the values when switching between weights.

**Comment by justvanrossum** [comment]
This is almost done as part of #483.
