### ISSUE TITLE
Right info panel: sort the axes in alphabetic order

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#468]
In the right info panel, sort the axes in alphabetic order

**Comment by justvanrossum** [comment]
> Also have the three main axis always at the beginning (width, height, weight), while the rest are sorted in alphabetic order

That's going to be tough, as a variable component axes don't really have a concept of "main" or "not main".

**Comment by mrk-z** [comment]
In that case would it be possible to have the axes starting with a lowercase letter at the beginning, followed by others starting with a capital letter?

**Comment by justvanrossum** [comment]
It would be possible, but it is a rather arbitrary order, specific to your project.

The other way around would be more natural (caps come before lowercase in Unicode and ASCII). So it you'd like a two-level hierarchy, it would be more natural to name the "main" ones with a cap, and the others with a lowercase letter.

**Comment by kenmcd** [comment]
This is similar to how the axes are sorted in GF variable fonts file names.
First, the lowercase "standard" axes in alphabetical order.
Then, the uppercase "custom" axes in alphabetical order.
I assume that is coming from fontmake or gftools or ???
Do not think it is manual - so it is coded somewhere.

**Comment by justvanrossum** [comment]
FWIW, the context here is local axes for variable glyphs, which is a font-designer-facing UI. They are not visible to end users.

We can decide on such a scheme, but without the context of VF "registerd axes" vs "custom axes", to sort lowercase before uppercase is quite arbitrary.

**Comment by mrk-z** [comment]
The naming scheme was mostly carried over from the previous project, so I'm not sure about the original reason for naming the axes like this. 
But we thought it made sense so we kept it: capital letters for abbreviations  (stroke names, position of the stroke, etc. which usually have limited options), and lowercase for longer words (usually what the axis actually modifies, weight, height, curve, etc, which could get complicated) in order to be clear and also save space.
