### ISSUE TITLE
Add a keyboard shortcut for switching between sources

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#487]
It'd be great to have a keyboard shortcut for switching between sources, while staying in the editing area. Maybe some combination of shift/cmd/ctrl/opt + arrow keys

One situation I encountered was that I needed to move the same two points in every source. Then it'd be helpful to be able to go to the next layer directly, while staying in the editing area with the same points selected.

**Comment by justvanrossum** [comment]
I implemented it as command-arrow-up and command-arrow-down.
