### ISSUE TITLE
Synchronize edits in all sources

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#493]
It'd be great to be able to make the same edits across all sources, and still keep them compatible. It's helpful for making design changes to a component that already have many sources.

Not sure to what extent this is possible. At the very least, adding/deleting a point at the same location of a contour would already be great.

Examples:
I want to add a small cut to a corner of a stroke. So I'm imagining being able to add a point at roughly the same location in each source and then going into each source to edit them.
I want to add a "bend" axis to a straight stroke, and I'd need to add handles to the same segment in all sources.

**Comment by justvanrossum** [comment]
Definitely on my wish list, too! We need to figure out the UI for this. Some ideas we've discussed in the past:
- Select multiple source in the source list by shift-click
- Have a flag in the source list that says "edit this one also"
- Have a tool option (alternate pointer tool) that edits through all sources

In your experience, would you like to be able to do certain operations in selected sources, or rather usually in _all_ sources?

Some operations change interpolation compatibility: the should probably always be done in all sources, if the behavior is clear and predictable.

**Comment by mrk-z** [comment]
Yeah I think it depends on the operation too. Things like adding points should definitely be done to all sources. But I imagine there are situations where I'd want to move a stroke down 20 units in all the "flat" sources, then it'd be good to be able to choose only those sources.

**Comment by justvanrossum** [comment]
Relates to #75
