### ISSUE TITLE
[bug] Creating new glyph jumps back to the previous glyph

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#497]
If I already have a non-unicode glyph (like a component) in the text box, creating a new glyph after it (by typing a character -> double click -> create) would jump back to the same non-unicode glyph, instead of staying in the newly created glyph.

(It's working fine if I already have a unicode glyph and then trying to create a new glyph.)

**Comment by justvanrossum** [comment]
Very interesting bug! I don't think it has to do with unicode vs no unicode, but whether a glyph was selected from the search list or not.

**Comment by mrk-z** [comment]
ah yes I tested it again, and it's like that
