### ISSUE TITLE
Preview for components in glyph list

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#499]
It'd be great to have some sort of preview for components in the glyph search list (also in the "Add Component" search box). Currently we name the components with unicode, and we'd have to search somewhere else for the unicode of the component we'd like to use, then come back to the glyph list to find it.

Alternatively, since we are naming the components with unicode (with some extra suffixes and prefixes), it'd be just as good if the glyph search list can read the unicode part of the name, and show the character in front of it like the unicode glyphs (maybe with a different color or a symbol to differentiate). Then when searching, if we type 口, it would return both the character glyph 口 as well as the component 口（for Chinese speakers we usually know how to type the majority of the components, so it'd be much faster to search like that)。

**Comment by justvanrossum** [comment]
Good suggestions. I see two levels of implementing this:

1. If a character is entered in the search field, also search for the hex value of the code point as if it were entered as a search string (but case-insensitive). For example when entering "口" (`U+53E3`) in the search field, we also show results as if we'd be searching for the string `53E3`, so we'd catch `VG_53E3_00` in addition to the encoded `uni53E3` character.
2. Parse any unencoded glyph name, and show a matching character if  4-5 char hex string is present in the glyph name. As you suggest, to show this in an alternate color would be good to distinguish it from a properly encoded glyph.

In both cases there may be a chance for a wrong match, though. The search results (for point 1) would then show a false positive. For the second point it may be less nice: it would show a wrong character.

I'll definitely implement the first point, and I'll think a bit more about the second.
