### ISSUE TITLE
[unittests] Write unittests for utils.js

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#510]
Several function in utils.js that can be tested are not. It would be nice if the ones that are easily testable (without mocking broswer stuff) are acually test.

We should create a file `test-js/test-utils.js`, and follow the patterns used in the other test files, using `chai` for the "expect" assertions.

The (easily) testable function are these (in order from the file, which is rather arbitrary):

- [x] `objectsEqual()`
- [x] `capitalizeFirstLetter()`
- [x] `hyphenatedToCamelCase()`
- [x] `modulo()`
- [ ] ~`sign()`~
- [x] `boolInt()`
- [x] `reversed()`
- [x] `enumerate()`
- [x] `reversedEnumerate()`
- [x] `range()`
- [x] `chain()`
- [x] `makeUPlusStringFromCodePoint()`
- [x] `getCharFromUnicode()`
- [x] `guessCharFromGlyphName()`
- [x] `fileNameExtension()`
- [x] `arrayExtend()`

We should not forget to test exception cases: `expect(...).to.throw(...)`.

Ideally we'd use a data-driven approach, similar to how `test-cmap.js` is written.

**Comment by fatih-erikli** [comment]
Btw there is a `sign` method in JS's `Math`, `(Math.sign)` for a sign function. Is there a reason it's implemented explicitly in utils? @justvanrossum

**Comment by justvanrossum** [comment]
> Btw there is a sign method in JS's Math, (Math.sign) for a sign function. Is there a reason it's implemented explicitly in utils?

Ah, good catch: this is a simple oversight. We should remove it from utils and use Math.sign() instead. (It strangely enough doesn't exist in Python's math module, so maybe that's why I failed to even look for it in JS.)

**Comment by justvanrossum** [comment]
Even worse: there is a second `sign()` implementation in `var-model.js`...

**Comment by justvanrossum** [comment]
This was implemented in #533.
