### ISSUE TITLE
select only on-curve / off-curves points

### ISSUE THREAD

**Issue by GaetanBaehr** [googlefonts/fontra#511]
Would be nice to have an option to select only the on-curves and/or only the off-curves points

**Comment by justvanrossum** [comment]
Hm, the "only off-curve points" thing is new to me.

What I was thinking is to make a preference for rectangle-select behavior:
- Default: like now, rect-select selects any point in the rectangle, whether on-curve or off-curve
- Opt-in with a preference: behave more like RF in that rect-select would only consider on-curve points

The third option ("only off-curve points") sounds more like something you'd like to switch often. But we already have meanings for most modifier keys, the UI for this would be unclear.

**Comment by GaetanBaehr** [comment]
In RF by default it select only the on-curves, and Opt-in will select only the off-curves. 
This is a feature that personally I use a lot

**Comment by justvanrossum** [comment]
"opt-in" means there would be a preference that will enable the behavior. I didn't mean the alt-key.

I didn't know about that alt-key thing in RF. In Fontra, alt-select has a different meaning: add to the selection. (Unlike shift, which inverts the selection.)

**Comment by justvanrossum** [comment]
#537 made Fontra's behavior match RF's behavior quite closely. (Not yet deplyed, but soon.)
