### ISSUE TITLE
Add "Add component to glyph" functionality

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#53]
Most likely the main entry point for this will be a contextual menu. See #146

**Comment by GaetanBaehr** [comment]
Started to work on UI for adding component

<img width="356" alt="image" src="https://user-images.githubusercontent.com/45567679/194508141-a30d596f-c87e-47f4-836f-cc433bb9fbac.png">

**Comment by justvanrossum** [comment]
This was implemented by #375. See also #319.
