### ISSUE TITLE
Have visual cues to differentiate a character glyph from a component

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#551]
It'd be nice to have a little more visual cues to differentiate between a glyph and a component, especially when you double-click on a component to edit it. 

Currently when I double-click into a component, I'm sometimes not sure which one is which, or even a little disoriented : they have the same color, same axis adjustments, and the only difference is the position; if I'm zoomed in while double-clicking on a component, it might jump to an unexpected view, and it takes a little time to find where I am on the canvas.

It happened a few times I thought I was editing the character glyph, but I was actually on the component.

Maybe a different shade of color for the background when in a component? a transition animation to show you're moved into a component? always centering the component when clicking into it?

https://github.com/googlefonts/fontra/assets/56224289/6148ebca-f85e-4575-8a94-3f692e697862

https://github.com/googlefonts/fontra/assets/56224289/bb9d82f7-9086-415a-8af9-b3771dbf049c

**Comment by justvanrossum** [comment]
But "in a component" doesn't mean anything. A glyph that uses components is not fundamentally different from the glyph that is being used as a component. So I'm not sure how this would practically work.

**Comment by justvanrossum** [comment]
Maybe "double click to go to the component" is too easy, and this action should rather be something more explicit, such as via the context menu?

**Comment by mrk-z** [comment]
Yeah maybe that. Since going from text view to edit view is also double click, sometimes I find myself clicking too many times going directly into the component.

Also maybe have some sort of transition when going into a component, like what the target button does, sort of recentering the component, instead of an abrupt jump, to help orient the user? or maybe landing directly into the edit view of the component with outlines, instead of showing both glyphs in text view with filled black colors?

**Comment by justvanrossum** [comment]
All good suggestions, thanks!

**Comment by justvanrossum** [comment]
This was fixed by #580. I don't think further work is needed here.
