### ISSUE TITLE
Add a "Location is not a source" warning when interacting with right panel

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#555]
Currently when the location is not a source, and I try to edit something in the edit area, I would get a warning. But if I try to do something in the right panel, like moving sliders or changing advance width, I don't get any feedback: it just gets stuck there and looks like a bug. 

It'd be nice to have the same warning too. Currently it might take a while to figure out what's happening, especially for those who are not familiar with Fontra.

**Comment by justvanrossum** [comment]
The Info panel is still slated for a rewrite, so this could be improved as part of that.

**Comment by justvanrossum** [comment]
This has been implemented as part of the recent selection info panel reworking.
