### ISSUE TITLE
User docs: need a plan / outline / schedule

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#588]
### Discussed in https://github.com/googlefonts/fontra/discussions/587

<div type='discussions-op-text'>

<sup>Originally posted by **davelab6** June 26, 2023</sup>
What's the plan, forecast, schedule, for user docs, so that a random pro level type designer can get started using Fontra?</div>

**Comment by ollimeier** [comment]
@justvanrossum There is also this issue related to Docs for type designers. 
@JeremieHornus Please see the conversation https://github.com/googlefonts/fontra/discussions/587

I guess the next step would be to make a fork of the current location to googlefonts or blackfoundry. Then we can close this issue, but keep it in mind as an ongoing issue. It would be also great to have a subdomain of fontra.xyz for the user documentation, something like docu.fontra.xyz or fontra.xyz/docu which then links to the github page

**Comment by ollimeier** [comment]
@justvanrossum I am closing this issue, because the docs repository has been moved to googlefonts successfully. Keeping the documentation up-to-date is an ongoing projects.
