### ISSUE TITLE
[sidebars] Sidebar misc items, related to resizing

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#590]
I have some followup feedback on #583:

- [ ] Toggling the sidebar doesn't animate anymore (the "animating" class)
- [ ] The "gutter" element to drag the sidebar width takes up space _in addition_ to the margin. The margin + gutter space should be the same as the "old" margin
- [ ] Sliders in sliders tab don't grow with sidebar

**Comment by fatih-erikli** [comment]
There is also a typo in tests. I will fix them.

How about minmax?

**Comment by justvanrossum** [comment]
Yeah, feel free to tackle minmax/clamp as well.

About the gutter: perhaps the gutter elements should be positioned absolute, so they don't interfere at all with the rest of the layout?

Also: the sliders in the sliders tab don't get wider when the tab gets wider. I'll add a checkbox to the description.

**Comment by fatih-erikli** [comment]
> About the gutter: perhaps the gutter elements should be positioned absolute, so they don't interfere at all with the rest of the layout?

Ok, it's possible. This will fix the second checkbox I guess?

**Comment by justvanrossum** [comment]
> Ok, it's possible. This will fix the second checkbox I guess?

Yes! Perhaps it can even be a narrow area overlapping the canvas, so that the user can aim exactly at the split, instead of "a little on the inside of the tab". If you know what I mean.

**Comment by justvanrossum** [comment]
There's some weir behavior in Safari when dragging the gutter: it thinks we're selecting text... Not happening in Chrome or Firefox.

https://github.com/googlefonts/fontra/assets/4246121/776263bc-f589-4354-b543-e19ecd51ab4e

**Comment by fatih-erikli** [comment]
This is misbehaving user-select. I've done it for "No selection" text, it's good there. I should have done it for the whole document when the resize is happening. I will fix that.
