### ISSUE TITLE
[editor] "Can’t edit glyph" dialog should be refined

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#591]
If the editor is not "at a source", and the user tries to move a point or component, we get a dialog that says:

    Can’t edit glyph “<name-of-glyph>”
    Location is not at a source.
                      (( Okay ))

What it should do instead is:

    Can’t edit glyph “<name-of-glyph>”
    Would you like to create a new source or navigate to the nearest source?
      ( Cancel )  ( Create new source )  (( Go to nearest source ))

**Comment by fatih-erikli** [comment]
I receive an error in console when I try to edit a glyph that it's source deleted.

```
varGlyph.sources[glyphController.sourceIndex] is undefined
```
