### ISSUE TITLE
Axis values carried over between components in a string

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#604]
If I have multiple components in the text string and switch between them, the axis values in the left panel would be carried over if they have the same axis name. 

So if I edit component A then go to component B, in the left panel of B the axes would have the same width/height/weight value as A. Then when I adjust the axes in B, B would first jump to the location of A, which means I lose the original location of B.

I think it'd be better if the values could stay separate and unchanged between components?

https://github.com/googlefonts/fontra/assets/56224289/17fcdf3d-9b5b-4ff5-8764-9f7891793617

**Comment by justvanrossum** [comment]
I'm confused by what you are trying to do, and what behavior you're actually describing. For example, when you say:

> the axis values in the left panel would be carried over if they have the same axis name

Do you describe what's happening now or what you would like to happen?

I'm not sure if you're looking at behavior that I intended but isn't useful, or whether you're looking at a bug.

Can you (privately) share the URL of the view you're looking at?

**Comment by mrk-z** [comment]
I was describing the current behaviors. For example, I have 2 components in the text string: A (width=100/height=100) and B (width=50/height=50). When I change A to width=200/height=200, and then go to B, the axis values of B have also been changed to width=200/height=200 (even though at first B still appears as width=50/height=50, if I move the axes the interpolation immediately jumps to width=200/height=200). 

What I think would be more useful is that the axis values stay independent: when I change A to width=200/height=200, and then go to B, B still stays as width=50/height=50. This way I could have multiple components open in the canvas and switch between them when editing.

(I wasn't sure if this was intended or a bug either 😅)

**Comment by justvanrossum** [comment]
Yeah, I think the intention is that they stay independent, and that there's a bug. Thanks for the further explanations!
