### ISSUE TITLE
[ruler] Ruler doesn't update correctly when moving elements

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#631]
Currently when I have the ruler on and move an element (a contour or a component) with the arrow keys, sometimes the measurements don't update correctly on the first movement : they stay unchanged, or sometimes go the opposite direction (e.g. I increase the distance between 2 shapes by 1 unit, but the ruler shows the distance is decreased by 1 unit).

Then if I keep moving it with the arrow keys, the error is kept (meaning the measurement continues to be one or more units off), unless I select the ruler tool again to measure it.

https://github.com/googlefonts/fontra/assets/56224289/5da7052d-56fa-4d7e-a787-10d2fe5451c4

https://github.com/googlefonts/fontra/assets/56224289/912e7496-1e94-4981-9772-013c37b1d33e

https://github.com/googlefonts/fontra/assets/56224289/f0c5286b-35db-427a-a274-e6a86880eff3

Moving the shapes with the mouse seems to work fine with the ruler

**Comment by justvanrossum** [comment]
I see, thanks for reporting! Will fix ASAP.

**Comment by justvanrossum** [comment]
Fixed and deployed.
