### ISSUE TITLE
Make "status" changes on multiple sources at a time

### ISSUE THREAD

**Issue by YuxinBlack** [googlefonts/fontra#643]
It will be useful to be able to select multiple sources and delete sources/change source status at the same time

**Comment by justvanrossum** [comment]
Also relates to #493.

**Comment by justvanrossum** [comment]
About the status: I don't think we track the status if individual sources for VGs, only on the default source. I think per-source is only done for CGs. Having your proposed functionality would still help there of course, but I was wondering whether you were trying to set that status on all VG sources.

Speaking of which, maybe we should change the default "RED" to "nothing", to make it clearer the status is simply not set.
