### ISSUE TITLE
Fontra scripts won't load

### ISSUE THREAD

**Issue by madig** [googlefonts/fontra#646]
When launching fontra from a git checkout, I get these errors in Firefox:

```
Loading module from “http://localhost:8000/third-party/lit.04d006ff.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://localhost:8000/third-party/lit.04d006ff.js”.
Loading module from “http://localhost:8000/third-party/bezier-js.04d006ff.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://localhost:8000/third-party/bezier-js.04d006ff.js”.
```

Chrome says:

```
Failed to load resource: the server responded with a status of 404 (Not Found) (lit.04d006ff.js:1)
Failed to load resource: the server responded with a status of 404 (Not Found) (bezier-js.04d006ff.js:1)
```

When launching Fontra Pak, I get even more errors and no UI. Not sure what this means... uBlock is disabled in both browsers.

**Comment by justvanrossum** [comment]
Which OS? Maybe there's something wrong with how mime types are determined.

It works for me on macOS 10.15 + recent Firefox.

**Comment by justvanrossum** [comment]
Can you tell me the output of the following command?
```
python -c "import mimetypes; print(mimetypes.guess_type('test.js'))"
```

**Comment by justvanrossum** [comment]
We've had a similar mime type problem before (#575) so now I'm worried that `mimetypes .guess_type()` is even more useless than I thought. It's a fairly trivial mapping for Fontra, though, so it'll be easy to replace.

**Comment by justvanrossum** [comment]
Would you look at that: https://github.com/tensorflow/tensorboard/pull/3128/files I bet this is our issue as well.

**Comment by justvanrossum** [comment]
I've merged a fix that I am fairly confident about: I could reproduce the error messages in Firefox when I deliberately used the wrong mime types. But not your Chrome messages, so that makes me doubt.

Please reopen if the problem persists.

**Comment by madig** [comment]
Can't reopen, but problem persists with same error :(

**Comment by justvanrossum** [comment]
Are you sure you upgraded / installed correctly?

**Comment by madig** [comment]
Uh, I did a git pull and then `hatch run fontra --launch filesystem <...>`. It happens on my Windows work PC (Windows and WSL) and my personal Linux PC :shrug:

**Comment by justvanrossum** [comment]
Ok, it doesn't work with "hatch run", but works for me (macOS + Windows) with a "manual" venv. Can you confirm it works with a manually created venv for you?

It may be some unexpected interaction with https://github.com/googlefonts/fontra/blob/main/scripts/rollup_build_hook.py, which writes some stuff to `src/fonts/client/third-party`. Perhaps "hatch run" causes this to be written to a tmp folder or something?

**Comment by justvanrossum** [comment]
I'm trying to find out hat magic hatch does, and how to even operate it, and I'm hitting all sorts of walls.

If you can figure out how to make Fontra work with "hatch run": I'd welcome a PR.

**Comment by madig** [comment]
Can confirm. What is this black magic.

Maybe I'll look at hatch one day.

**Comment by justvanrossum** [comment]
Fontra's build hook uses npm to prepare the runtime npm dependencies, and writes them into the source tree (`src/fontra/client/third-party/`), where the Fontra server can find them. 

This is conceptually the same as what the "vcs" hook does: write stuff in the source tree that not tracked by git, but is needed at runtime.

**Comment by justvanrossum** [comment]
Perhaps all that needs to be fixed is to add the written file paths to the artifacts list, like the vcs hook does:

https://github.com/ofek/hatch-vcs/blob/425d529cd24295311ca5b52b589a6308165fb244/hatch_vcs/build_hook.py#L45C9-L45C9

**Comment by justvanrossum** [comment]
Can you try with the `fix-build-hook-issue646` branch, from PR #651?

**Comment by justvanrossum** [comment]
I find it really hard to test, because "hatch run" doesn't seem to re-run the build hook when I changed it, and I don't know how to tell "hatch run" to start from scratch.

**Comment by justvanrossum** [comment]
Ah, it also relates to this:

https://github.com/googlefonts/fontra/blob/e59fe42754cbb8e5b2d4ffeff43e716ed11a9478/pyproject.toml#L72-L76
This causes the build hook artifacts to be only included then the build target is a wheel. 

This is intentional, though: these artifacts should _not_ end up in a source distro. It happens to also work correctly when doing `pip install -e .`, but apparently not for "hatch run".

All #651 is doing is unconditionally include the artifacts, but I'm not sure I want that.

**Comment by madig** [comment]
Will try soon, but you can level a hatch env with `hatch env prune`.

**Comment by justvanrossum** [comment]
Thanks, that's very useful.

Now the weirdest thing: I can't get it to fail anymore at all on Windows (on the main branch). So I still quite can't put my finger on why it didn't work before, or why it didn't/doesn't work for you.

I see pip and virtualenv have had releases since you opened this issue. Perhaps the issue went away with these (or other) updates.

I'd be curious to know if the problem also went away for you.

**Comment by madig** [comment]
Yeah, it works now via hatch run, even on Windows. Witchcraft.

**Comment by justvanrossum** [comment]
Thanks for confirming!
