### ISSUE TITLE
[bug] Compatibility issue when adding new axis to a component within another component

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#655]
Currently we're running into this bug:

We already have a component A, and another component B which includes component A within it. If we add a new axis to A and make sure everything works well within A, then B would report a compatibility issue and stop interpolating, despite that everything is actually compatible.

So far we've found that the issue resolves itself after logging out then re-logging in; or if we go into every source of B, select component A, and move around the slider of the newly added axis.

**Comment by justvanrossum** [comment]
Let me try to summarize in discrete steps:

- A is a variable glyph (itself made of components (?), but I'm not sure that's relevant)
- B uses A as a component
- In RoboCJK, you add an axis to A
- In Fontra you add sources for the new axis to glyph A (?)
- Glyph B now no longer interpolates, despite that it should
- Logging out then in resolves the problem, and now Fontra happily interpolates B

Please correct if this doesn't reflect what happened.

**Comment by mrk-z** [comment]
Yes that's right!

And I don't think it matters whether A is made of components or contours. I believe I've run into this issue regardless of that.
