### ISSUE TITLE
Indicate which sources contribute to interpolation of current glyph

### ISSUE THREAD

**Issue by madig** [googlefonts/fontra#660]
More a nice to have than anything else, but it would be useful when hunting down which-source-is-interfering-with-my-interpolation bugs if the source list would indicate which sources contributed to the current interpolation, i.e. where the variation model gets its data from. A bit like Samsa maybe, but for font sources.

**Comment by justvanrossum** [comment]
Nice idea. Fontra definitely needs a way to debug interpolation problems. 

The first thing I’d like to implement is an indicator in the source list that says whether a source is not compatible.

**Comment by justvanrossum** [comment]
> it would be nice if one could "turn off a source", as in, make it not participate

That’s what the checkbox left of the source name does.

**Comment by justvanrossum** [comment]
https://github.com/googlefonts/fontra/assets/4246121/39dd384a-6056-451c-a187-ef93cbb116ff

**Comment by belluzj** [comment]
Amazing! Thanks @justvanrossum
