### ISSUE TITLE
[bug] Interpolation bug when adding new axis to a component within another component

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#669]
Relates to #655 

The previous compatibility bug has been fixed, but an interpolation bug has appeared under the same circumstances as in #655 :

- A is a variable glyph
- B uses A as a component
- In RoboCJK, add an axis to A
- In Fontra add sources for the new axis to glyph A
- Now Glyph B sometimes interpolates as if the newly added axis is set to max value, even though the axis itself is at 0. This happens only to certain sources/weights at a time -- sometimes only to hairline, sometimes only to extrabold.
- Moving the slider of the newly added axis, or logging-out and re-logging seems to solve the visual bug temporarily.

**Comment by justvanrossum** [comment]
It may also be related to #604. I'm working on a larger change that will include a fix for that, and I suspect this bug, too.

**Comment by justvanrossum** [comment]
This needs verification whether it indeed has been fixed. I'll let you know when it's deployed so you can check.

**Comment by justvanrossum** [comment]
@madig can you check again whether this still happens? There's a good chance it is fixed now.

**Comment by justvanrossum** [comment]
@mrk-z can you check again whether this still happens? There's a good chance it is fixed now.

(Sorry @madig, I mistagged you)
