### ISSUE TITLE
[bug] Opening a Fontra link clears the text box

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#688]
Recently we've been having this problem, where when we open a link that someone sends over, or a link that we previously saved, it opens up a blank canvas page, with no texts in the text box. 

Today I also encountered a situation where when I reload the page, it also clears the text box.

**Comment by justvanrossum** [comment]
Please send me such a link privately.

**Comment by justvanrossum** [comment]
It seems an intermittent problem, but I have been able to reproduce after a few tries. I'll try to debug.

**Comment by justvanrossum** [comment]
I can't reproduce the problem anymore, so I suspect I have now sufficiently fixed it.
