### ISSUE TITLE
[bug] Axes stop responding briefly after the initiation of each action

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#693]
The axes stop responding about 1 second after we start an action.

If I try to drag the slider with the mouse, the slider would follow the cursor for a little and then stops.

https://github.com/googlefonts/fontra/assets/56224289/06d2fe48-ccb1-4e2b-977f-056e097955b4

If I try to change the axis value with the arrow keys, it would exit the text box by itself right after I press an arrow key. So I can only manage to change the value by 1. Or if I press the arrow key very quickly multiple times, I might be able to change it by 3 or 4.

https://github.com/googlefonts/fontra/assets/56224289/014e7a0a-7660-4bb5-846e-13b01c9ce23a

This starts to occur only today.

**Comment by justvanrossum** [comment]
Hm, I see, this is indeed a recent regression. Will fix as soon as possible.
