### ISSUE TITLE
Add an indication when there is a compatibility issue

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#704]
It would be great to have some sort of indication to show when a glyph is not compatible. (for example, in Glyphs a non-compatible glyph always has a red Bar on top.) Currently we would only know it after we try to move the sliders, so sometimes it's easy to miss. 

Also I think it would be helpful to more designers if the error messages at the bottom of the screen are somewhat more straightforward, or maybe include some sort of recommended actions. Sometimes we need to figure out what the error messages actually mean.

**Comment by justvanrossum** [comment]
Relates to #700 and #660.

**Comment by justvanrossum** [comment]
The source list now shows which sources aren't compatible with a little "bug" icon. Not 100% what you are asking for, but better than nothing.

**Comment by justvanrossum** [comment]
> In other words, if we see something like this, we should read it as it's more likely that something is wrong in the default layer?

Yes. There has to be _some_ reference, and indeed the default is chosen.

I'm thinking of how to improve this: perhaps if all "buggy" sources are compatible with each other, it would be a clear indication the the bug is actually in the default source.

**Comment by justvanrossum** [comment]
(The difficulty in doing this "right" is in finding a reasonable answer to "which source is suitable as the reference source", without having to compare every source with every other source, as that would scale very poorly with large numbers of sources. A fun challenge nevertheless...)

**Comment by justvanrossum** [comment]
> Does it always determine compatibility based on the default layer?

This has been fixed now (and deployed).

**Comment by justvanrossum** [comment]
Maybe a louder "incompatible" warning is needed in the canvas, but or now the source list indicator will have to do.
