### ISSUE TITLE
[bug] Component import values from other layers for new axes added to a component within a component

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#708]
Relates to #655 and #669

Similar to the previous scenarios, now when I add axes to a component within another component, and then use these axes in the character, sometimes one layer would copy the axis values from another layer.

For example, I recently added these axes to one of the component within this component, and then in this character, I used these axes in other weights, but not the Hairline weight. However, today I saw that in the Hairline layer it copied the values for these axes from the default layer.

<img width="934" alt="Capture d’écran 2023-08-09 à 14 47 00" src="https://github.com/googlefonts/fontra/assets/56224289/f1326b67-79ad-4806-b243-44e2f3109951">

I noticed this while I was testing for #669 but I thought it might have been the result of fixing the previous bug. But for the example shown above, the axes were added this week.

**Comment by justvanrossum** [comment]
I have a real hard time understanding what exactly you mean.

We are looking at a glyph that uses a component. The axes that you can use on a component are defined by the glyph that the component references.

Terminology: a glyph that uses a compoinent _is not a component itself_, although _the glyph can be used as a component elsewhere_. A component references a glyph. That glyph can be called "base glyph".

A "component within a component" makes no sense to me, so I assume you mean: a glyph that uses a component to reference another glyph, which uses a component that references yet another glyph. Or something like it. But the problem you are describing does not seem to be related to such deep nesting per se.

Anyway, maybe we should have a call you can demonstrate.

**Comment by mrk-z** [comment]
Sorry about the confusion.

It's similar to the previous situations. (But in this specific example it involves 3 glyphs, not sure if that matters.)

- A is a variable glyph
- B uses A as a component, C uses B as a component
- In RoboCJK, add an axis to A
- In Fontra add sources for the new axis to glyph A
- In RoboCJK, add an axis to B
- In Fontra add sources for the new axis to glyph B
- Now in glyph C, in source 1, change the value of the newly-added axis of B. Later (it seems it's not immediate) in source 2, the same axis (whose value had not been modified before) copies the exact value from source 1.
