### ISSUE TITLE
Stay in the canvas after using sliders in the left and right panels

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#710]
Currently if we make an edit in the canvas, and then go use a slider or add a source in the left/right panel, then the slider or the sources section become the active area. If we press the arrow keys it would just move the sliders. Then we need to click in the canvas again to go back to edit, and/or reselect the things we have previously selected.

I think it would work better if we use a slide or add a source in the middle of editing, the canvas remains as the active area, so that we could continue editing the same elements. 

One situation is that while making components, we would, for example, drag a slider to one end -> add a source -> move a shape up 200 units -> drag the slider to the other end -> add a source -> move the same shape 200 units to the opposite direction. Currently after we each use the slide or add a source, we have to reselect the same shape, even though the same shape shows as selected. If the same shape can stay selected and active, it would save a lot of clicking and re-selecting.

(I think typing something in the axis value box is less of a problem, because the text box is highlighted and we expect the arrow keys to change the numbers. I think it's mainly the sliders and adding sources.)

**Comment by justvanrossum** [comment]
I think see what you mean, will look into it.

**Comment by mrk-z** [comment]
I think this applies to pop up dialogue boxes too.

For example, currently if I try to move a point at a location where there is no existing source, I get a pop-up notification that suggests adding a source. But after I click New Source -> Add, I have to reselect the same point in order to keep editing.

Or if I right-click -> Add Component, I cannot immediately use arrow keys to move the newly-added component, even though the component is highlighted. I have to select the component with the mouse again in order to move it with arrow keys.

I think it would work more smoothly if we don't have to remake the selection after resolving a dialogue box.

**Comment by justvanrossum** [comment]
Yes, the focus should stay on the canvas in all the cases you mention. In terms of implementation, the dialog issue is separate from the slider focus issue, though.
