### ISSUE TITLE
Stay on the selected/edited source in the sources section after an edit

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#711]
Currently in the sources section in the left panel, if we make an edit to a source, for example activating/deactivating it, changing its location or status, it would jump to the top of the list of sources. 

It'd be great to be able to stay on the selected/edited source, so that we don't have to find it in the list after each change, as often we would want to edit multiple sources next to each other.

**Comment by justvanrossum** [comment]
Can you elaborate? If I select a source, and activate/deactivate the source, or change the status, I don't see any jumping in the list.

**Comment by mrk-z** [comment]
Like this:
https://github.com/googlefonts/fontra/assets/56224289/2525945a-0965-4b85-bb71-e77525b34d94

**Comment by mrk-z** [comment]
Like this:
https://github.com/googlefonts/fontra/assets/56224289/e3974f2d-6152-4726-aaa5-dd5394a17596

**Comment by justvanrossum** [comment]
Ahh now I understand: it is about scrolling when the list is longer than the view.
