### ISSUE TITLE
Alignment tool for outlines and components

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#720]
An alignment tool would be very helpful. Ideally it would work for both outlines and components, and be able to align objects to each other or to the frame.

**Comment by ollimeier** [comment]
Might be part of the transformation panel. 
I can imagine a similar design and functionality to InDesign:
https://helpx.adobe.com/indesign/using/aligning-distributing-objects.html#:~:text=You%20can%20use%20the%20Align,margins%2C%20page%2C%20or%20spread.&text=Select%20the%20objects%20to%20align,to%20display%20the%20Align%20panel.

@justvanrossum Do you have any ideas/suggestions? Should I use any specific functions/tools within Fontra?

**Comment by ollimeier** [comment]
This is how figma looks like:
<img width="1919" alt="Screenshot 2024-04-10 at 08 55 34" src="https://github.com/googlefonts/fontra/assets/21055547/38ffaece-6c61-47b4-979d-198930eec06a">

**Comment by justvanrossum** [comment]
I think they can indeed become part of the transformation panel.

The "layout-align" tabler icons may be usable.

**Comment by ollimeier** [comment]
Affinity Designer:
![ad_align jpg 6a8ae161d9d1488a46c474c98c57d467](https://github.com/googlefonts/fontra/assets/21055547/716d153d-bbce-46b5-9536-8b529f2da269)

PowerPoint:
![6a13ed66-57e0-4bca-bcee-a143d47075b4](https://github.com/googlefonts/fontra/assets/21055547/d3ae62db-71ad-41ba-8ebe-dd4595412105)

**Comment by justvanrossum** [comment]
The Figma ones are my favorites.
