### ISSUE TITLE
Custom shortcuts for tools

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#721]
It would be great to be able to customize shortcuts for the main tools (Selection, Pen, Measurement, etc.), for example assigning them to letter keys instead of number keys.

Currently there are a few issues with having the number keys as shortcuts:

1. If we first adjust an axis by typing a value or using arrow keys, and want to immediately switch to a different tool, pressing a number key directly would actually enter the number into the axis value box, and thus changing the axis value and the component. Currently we often find ourselves messing up axis values this way and having to undo the action, or need to be extra careful to make sure to click outside the axis value box first before switching tools. (It seems pressing a letter key would not enter the letter into the box.)

2. On standard French AZERTY keyboards, the number keys are shift-functions, so the number shortcuts require 2 keys.

Then some designers have expressed they are more familiar with letter keys as shortcuts for tools, similar to Glyphs or some other softwares (V for selection, P for pen, etc.)

**Comment by justvanrossum** [comment]
Custom shortcuts is for sure something we want.

That said:

> Then some designers have expressed they are more familiar with letter keys as shortcuts for tools

Fontra is not a drop-in replacement, so some muscle memory will have to be adjusted by users.

> similar to Glyphs

FYI. I am not super interested in matching anything from Glyphs specifically, to the extent that reading "similar to Glyphs" will often automatically lower it on my mental priority list.
