### ISSUE TITLE
Pasting component(s) to replace selected component(s)?

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#724]
This would be an easy way to copy the component settings from one source to another, which is a highly requested feature.

This is also an alternate way to achieve #456.

**Comment by mrk-z** [comment]
This would be useful when replacing an entire component. But there are cases where we only want to copy/paste/synchronize the value of one specific axis, so this might not be a complete alternate to #456.

**Comment by BlackFoundry** [comment]
superseded by multi-source editing.

**Comment by mrk-z** [comment]
I think this (or #456) would still be a needed feature.

This is more about replacing an existing component without distrubing the shape order/compatibility. Sometimes it's about pasting from one glyph to a specific source of another glyph, or copying/pasting between 2 components in the same source. In these cases they have nothing to do multi-source editing.
