### ISSUE TITLE
Styling + behavior of checkboxes in the source list

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#767]
Currently, the source list has two columns that use a checkbox. I would like them to be styled differently. Whether they should even remain an `<input type="checkbox">` is an open question.

<img width="785" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/49c56956-cf06-4f9c-a774-e857a16f7e20">

I would like to use icons from the tabler collection instead.

For the "on" column (reflecting the "inactive" source attribute), I would like to use [circle-dot](https://tabler-icons.io/i/circle-dot) for the "on" state, and [circle-dotted](https://tabler-icons.io/i/circle-dotted) for the "off" state.

Additionally, I'd like this control to be triggered by double-click only, as apparently people sometimes accidentally click it without understanding the consequences.

For the "bg" column ("visible in background"), I would like to use [eye](https://tabler-icons.io/i/eye) for "on", and [eye-closed](https://tabler-icons.io/i/eye-closed) for "off". (This one should remain "single-click")

Finally, I'd like the "bg" header to be replaced by the "eye" icon. This may be a bit more complicated as the list header mechanism currently only supports text. I'm not yet 100% how it should be done, and should be a separate task.

When using tabler icons, we copy them into the [tabler-icons](https://github.com/googlefonts/fontra/tree/main/src/fontra/client/tabler-icons) folder.

**Comment by fatih-erikli** [comment]
> Whether they should even remain an <input type="checkbox"> is an open question.

With some css tricks, it's possible to style a checkbox look like something different, however I propose not to use checkbox if they are going to be triggered by double-click only.

**Comment by justvanrossum** [comment]
> With some css tricks, it's possible to style a checkbox look like something different, however I propose not to use checkbox if they are going to be triggered by double-click only.

Well, I only want the "on/off" switch to be triggered by double-click. The "bg" should be "normal". But I know styling of checkboxes is cumbersome, so if it is easier to just use a div, I'm fine with that.
