### ISSUE TITLE
Ability to customize the height of sections in left and right panels

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#795]
It'd be good to be able to drag the dividers to adjust the height of various sections in the left and right panels.

**Comment by mrk-z** [comment]
Currently this mainly concerns the Axes tab in the left panel. Currently the Axes section and the Sources section normally each occupy about 50% of the overall height of the panel. However, in some cases where a glyph has many layers, the Axes section shrinks to about 1/6 of the overall height, and we are only able to see 3 axes at a time.

(maybe for a temporary fix, it'd be good to set the height of the Axes section to 2/3 of the overall height, as this is more often used than the Sources section.)

**Comment by justvanrossum** [comment]
Ah, this is actually a regression: the axis list used to shrink slower than the sources list. I'll fix that.
