### ISSUE TITLE
Improve tooltip positioning

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#798]
The tooltip code currently works well for the "Reset all axes" and "Edit local axes" buttons, but that's only because those labels have similar lengths.

The following improvements should be made:
- the tooltip should be centered
- except when it would be clipped by the window, then it can move

**Comment by justvanrossum** [comment]
It would be great if you and @fabiocaccamo could brainstorm about this. I'm not opposed to adding some JS for this, although it is kind of neat we currently don't need any JS.

**Comment by fatih-erikli** [comment]
If we add JS, let's switch it to a web component, or implement it in `icon-button`.

I noticed one thing, we put the tooltip text via `data-tooltip` attribute. Github uses `aria-label` for that. Maybe we will use aria tag, if we really care about a10n at that moment.

![Uploading Screen Shot 2023-10-05 at 10.34.51.png…]()

**Comment by justvanrossum** [comment]
I didn't know about ARIA: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

I'm not sure how we can use this.

> If we add JS, let's switch it to a web component, 

Let's first find whether we _must_ use JS at all to achieve this.

> or implement it in icon-button

No, this functionality has to be general.

**Comment by fabiocaccamo** [comment]
@fatih-erikli @justvanrossum as always there are different solutions, it depends by our specific needs and expectations.

A CSS only solution is surely possible, but with some limitations, for example this can't be done with CSS only:
> the tooltip should be centered, except when it would be clipped by the window, then it can move

Here some Pros and Cons of the different implementations:

**CSS**
- simple/faster development and implementation
- easier to maintain
- errors free
- position and size can be decided using just html attributes
- can't change behaviour depending on element position relative to the window

**JS**
- a bit more complicated/longer development and implementation
- harder to maintain
- there is margin for unexpected js errors
- position and size can be decided using just html attributes
- can change behaviour depending on element position relative to the window
- there are some popular well documented libs like: https://github.com/atomiks/tippyjs

---

Considering Pros and Cons I would opt for the CSS only solution making it more flexible as possible using many HTML attributes for defining the tooltip behaviour, eg. 
- `data-tooltip-text`
- `data-tooltip-max-width`
- `data-tooltip-position`: `top-left`, `top`, `top-right`, `right`, `bottom-right`, `bottom`, `bottom-left`, `left`

**Comment by justvanrossum** [comment]
But how to handle “edge of the window” case? Tooltips should never be cropped.

**Comment by fabiocaccamo** [comment]
I think that this could be avoided by using left-alignment on tooltips of elements on the left part of the window and vice-versa.

**Comment by justvanrossum** [comment]
That sounds good. Perhaps if we have a max width for the tooltip, the “left part” and “right part” would be half max wide, and the remaining space would center.

**Comment by fatih-erikli** [comment]
Thanks for the clarification @fabiocaccamo.

**Comment by fatih-erikli** [comment]
Looks like setting a width by attribute isn't supported yet.
https://developer.mozilla.org/en-US/docs/Web/CSS/attr#values

We can't set max width by data attributes therefore.

We may set a constant width for now. What do you think, @justvanrossum @fabiocaccamo, is there a workaround do you suggest?

A little bit detail of my struggle, we have no width set yet, I can't center the tooltip content. Something like `-50%` won't work in this case.

**Comment by fatih-erikli** [comment]
There is this workaround I found a workaround, I'll do it like this https://stackoverflow.com/a/70652364. I'll do it like that.
