### ISSUE TITLE
unlit.js should be renamed to html-utils.js

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#828]
`htmlToElement()` and `htmlToElements()` from utils.js should also move there.

Alternative name suggestions:
- `html-tools.js`
- `html.js`
- ... anything else?

Curious what you think.

**Comment by fatih-erikli** [comment]
Maybe `dom-utils.js`.

**Comment by justvanrossum** [comment]
Let's go with `html-utils.js`.
