### ISSUE TITLE
projectmanager.py, _iterFolder: skip dir entries with errors

### ISSUE THREAD

**Issue by madig** [googlefonts/fontra#853]
When opening a directory where you lack the permission to read some folders, it might be best to skip looking into dirs that cannot be read for some reason. Or warn the user somehow.

**Comment by justvanrossum** [comment]
Can you propose a fix? I haven't seen this situation.

**Comment by madig** [comment]
When I get around to it :) It can happen on a Linux system when pointing to /tmp, where a user lacks permission to read some dirs.
