### ISSUE TITLE
Show baseline (and alignment lines and zones)

### ISSUE THREAD

**Issue by BlackFoundry** [googlefonts/fontra#857]
- ascender
- descender
- cap height
- x-height
- blue zones?

Perhaps relates to custom guidelines.

**Comment by BlackFoundry** [comment]
Read FontInfos to show various alignement lines and zones. 
Question of variations across the design-space…

**Comment by justvanrossum** [comment]
Baseline we have:
![image](https://github.com/googlefonts/fontra/assets/4246121/95181353-2af6-4e49-aa66-a8fe0f19618b)

**Comment by BlackFoundry** [comment]
yes but we need xheight, descender, and cap-height, etc.

**Comment by BlackFoundry** [comment]
Related to #907

**Comment by bghryct** [comment]
Most of this is available now right? Blue zones are the only missing feature I think

**Comment by justvanrossum** [comment]
Yes indeed, looks like we forgot to link this issue to #1405.
