### ISSUE TITLE
Zoom in scrolling issue

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontra#890]
I'm using Fontra Pak on Windows with Chrome.

When using Ctrl+scroll down, the whole canvas just zoom out to minimum size unlike Alt+scroll down. Is it the default behaviour?

**Comment by justvanrossum** [comment]
It is probably something Fontra does wrong.

For reference, the relevant code is here:

https://github.com/googlefonts/fontra/blob/ad2d560f7e188dcc99a59215789fc9f0e4fc17ed/src/fontra/client/core/canvas-controller.js#L110-L126

I'm suspecting we're not doing the right thing with the wheel events.

**Comment by navv-1** [comment]
https://github.com/googlefonts/fontra/blob/ad2d560f7e188dcc99a59215789fc9f0e4fc17ed/src/fontra/client/core/canvas-controller.js#L114
I think the problem is here. On windows, deltaY value is -100 or 100. So, it will return 0 value when using ctrl+scroll down.

**Comment by NightFurySL2001** [comment]
Seems like this is using the `wheel` event. From MDN:
> Note: Do not confuse the wheel event with the scroll event. The default action of a wheel event is implementation-defined. Thus, a wheel event doesn't necessarily dispatch a scroll event. Even when it does, that doesn't mean that the delta* values in the wheel event necessarily reflect the content's scrolling direction. Therefore, do not rely on delta* properties to get the content's scrolling direction. Instead, detect value changes to scrollLeft and scrollTop of the target in the scroll event.

**Comment by justvanrossum** [comment]
FWIW, this is about scrolling on an HTML canvas, which doesn't scroll by itself (in the DOM Element sense), so we don't receive scroll events. We therefore need to handle wheel events to implement scrolling (and zooming).

It appears that the wheel event as supported by browsers is a lot less refined than what native apps (including browsers...) can do. The delta values vary quite a bit, depending on browser, OS, and input device (trackpad vs. mouse with scroll wheel), so the whole business of making things behave "decently" involves some ~messy guesswork~ heuristics, and may still not match platform-native scroll behavior perfectly. I hope #928 is a good step in the right direction, so we at least won't have completely broken behavior anymore.
