### ISSUE TITLE
[feature] shift-scrolling for horizontal scrolling

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontra#891]
I'm using Fontra Pak on Windows. By default on Chrome shift-scrolling should allow horizontal scrolling, but Fontra editor seems to only scroll vertically.

**Comment by justvanrossum** [comment]
This is probably an oversight.

**Comment by justvanrossum** [comment]
Same relevant code, FWIW:

https://github.com/googlefonts/fontra/blob/ad2d560f7e188dcc99a59215789fc9f0e4fc17ed/src/fontra/client/core/canvas-controller.js#L110-L126

Should it interpret deltaX as deltaY if shift is pressed? That would be an easy fix.
