### ISSUE TITLE
Show Unicode and character for glyphs with suffix in the name

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#895]
Currently on the top right panel, if the glyph name contains suffix, the "Unicode" section is blank.

It'd be helpful to still show unicode and the character for suffixed glyphs, so that we can copy and paste the character

**Comment by justvanrossum** [comment]
The unicode section shows whether the glyph is literally encoded with that unicode value. A glyph with an extension generally is not encoded. For example the glyph `A` is encoded as U+0041, but `A.sc` is not.

While I see the usefulness of what you're asking for, there needs to be some indication that this is a "guessed" unicode value, and not how the glyph is encoded.

**Comment by justvanrossum** [comment]
Or maybe not "guessed", but that it is based on the extension-less version of the glyph.

**Comment by justvanrossum** [comment]
We could call it "Base unicode"? It would be an additional line in the info section, but only if the glyph doesn't have a "proper" unicode, and only if we can actually determine the base unicode value.

**Comment by mrk-z** [comment]
Yes that sounds like a good idea!

**Comment by justvanrossum** [comment]
(This got closed accidentally)
