### ISSUE TITLE
Tool items / View items

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#9]
Tool items:
- [x] pointer
- [x] pen #30 
- [x] knife #190
- [x] measure #45 
- [x] shape tool (rect/oval) #198

View items:
- [x] scroll hand
- [x] zoom plus and minus
- [x] enter/exit full screen #189
- [x] recenter around selection / selected glyph

**Comment by ollimeier** [comment]
@justvanrossum The last missing checkbox was 'knife'. As this has been implemented a couple weeks ago I am closing this issue.
