### ISSUE TITLE
Start designspace/ufo project from scratch

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#906]
This is possibly a Fontra Pak feature, or relates to it.

**Comment by BlackFoundry** [comment]
Depends also on #907

**Comment by ollimeier** [comment]
@justvanrossum Do we want to close this as we have added it to fontra-pak or do we keep it for the new menu bar, which still has placeholders in grey?

**Comment by justvanrossum** [comment]
I linked it to #1063 now, so I’ll keep it open for a bit.

The reason is that without axis editing, starting a project from scratch is still very limited.

**Comment by justvanrossum** [comment]
Implemented via https://github.com/googlefonts/fontra-pak/pull/87
