### ISSUE TITLE
Add function to show status colour of glyphs in canvas

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#926]
It'd be great to have a function to toggle show/hide the status colour (of the default layer) of each glyph in the canvas, maybe as a background colour of each glyph, or a coloured bar at the bottom.

This helps to have an overview of the status of a specific set of glyphs that we input in the text box.

**Comment by justvanrossum** [comment]
I suggest to draw a colored rectange below the glyph, for now at a hard-coded position based on the upem (say, around -150 * unitsPerEm / 1000). As wide as the xAdvance, but relatively low (say, between 20 and 50 units). It should be shown in all glyphs, not just the edited glyph.

The definition of the status codes can be found in the font's customData. I'll provide you with an example font.
