### ISSUE TITLE
Rewrite range-slider to not use lit

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#939]

**Comment by fatih-erikli** [comment]
There's only one major problem I noticed when deleting lit. When we set a property, such as `value` on a slide event, we re-render the component. It deletes the html, puts the inputs, makes a lot of renders, lose the focus of current element.

**Comment by fatih-erikli** [comment]
I manually
- set the set the value of range input when number element is changed
- set the value of number element when range element is changed

**Comment by justvanrossum** [comment]
To avoid unnecessary rerendering, should we perhaps implement a setter/getter for value, instead of doing the automatic render via the properties list?

**Comment by justvanrossum** [comment]
I reverted #952, it had two serious regressions:
- The slider didn't work on fractional values anymore: step must be "any"
- Arrow key editing didn't emit events

**Comment by justvanrossum** [comment]
I had fixed the step issue in https://github.com/googlefonts/fontra/commit/268563b601023284be2e928f4e725e4d6d448565, but didn’t see a quick fix for the second item.

**Comment by justvanrossum** [comment]
Fixed by #971.
